//! End-to-end CLI contract tests for the autonomous TDD loop.
//!
//! These tests drive the real `envctl` binary through hermetic fixtures and pin the
//! machine-facing behavior the loop uses to decide whether a CLI gap is red/green:
//! root surface discovery, manifest-independent commands, fail-closed refusal exit
//! codes, and lock-check JSON truth.
use std::path::{Path, PathBuf};
use std::process::Command;

fn bin() -> &'static str {
    env!("CARGO_BIN_EXE_envctl")
}

struct Fixture {
    root: PathBuf,
    manifest: PathBuf,
    meta: PathBuf,
    xdg_config: PathBuf,
    xdg_data: PathBuf,
    xdg_cache: PathBuf,
}

impl Fixture {
    fn new() -> Self {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        use std::sync::atomic::{AtomicU64, Ordering};
        static SEQ: AtomicU64 = AtomicU64::new(0);
        let seq = SEQ.fetch_add(1, Ordering::Relaxed);
        let root = std::env::temp_dir().join(format!("envctl-cli-contract-{nanos}-{seq}"));
        let manifest = root.join("manifest");
        let meta = root.join("meta");
        let xdg_config = root.join("xdg-config");
        let xdg_data = root.join("xdg-data");
        let xdg_cache = root.join("xdg-cache");
        std::fs::create_dir_all(&manifest).unwrap();
        std::fs::create_dir_all(&meta).unwrap();
        std::fs::write(
            manifest.join("base.toml"),
            r#"
[[component]]
id = "stub"
name = "Stub Component"

[component.detect]
kind = "command"
command = "true"
"#,
        )
        .unwrap();
        std::fs::write(
            meta.join(".meta.yaml"),
            "projects:\n  envctl:\n    repo: git@github.com:FlexNetOS/envctl.git\n",
        )
        .unwrap();
        Self {
            root,
            manifest,
            meta,
            xdg_config,
            xdg_data,
            xdg_cache,
        }
    }

    fn cmd(&self) -> Command {
        let mut c = Command::new(bin());
        c.current_dir(&self.root)
            .env("ENVCTL_MANIFEST_DIR", &self.manifest)
            .env("XDG_CONFIG_HOME", &self.xdg_config)
            .env("XDG_DATA_HOME", &self.xdg_data)
            .env("XDG_CACHE_HOME", &self.xdg_cache);
        c
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        std::fs::remove_dir_all(&self.root).ok();
    }
}

fn stdout(out: &std::process::Output) -> String {
    String::from_utf8_lossy(&out.stdout).into_owned()
}

fn stderr(out: &std::process::Output) -> String {
    String::from_utf8_lossy(&out.stderr).into_owned()
}

#[test]
fn root_help_lists_the_full_cli_surface() {
    let out = Command::new(bin()).arg("--help").output().unwrap();
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    let help = stdout(&out);
    for verb in [
        "auto-detect",
        "graph",
        "registry",
        "lock",
        "doctor",
        "install",
        "reset",
        "auto-fix",
        "add-repo",
        "dashboard",
        "env",
        "agent",
        "self",
        "completions",
        "secret",
    ] {
        assert!(help.contains(verb), "root --help missing `{verb}`:\n{help}");
    }
}

#[test]
fn manifest_independent_commands_work_without_a_manifest() {
    let fx = Fixture::new();
    let missing_manifest = fx.root.join("missing-manifest");

    let env_out = Command::new(bin())
        .current_dir(&fx.root)
        .env("ENVCTL_MANIFEST_DIR", &missing_manifest)
        .args(["env", "--meta-file"])
        .arg(fx.meta.join(".meta.yaml"))
        .output()
        .unwrap();
    assert!(env_out.status.success(), "stderr: {}", stderr(&env_out));
    assert!(stdout(&env_out).contains("META_ROOT"));

    let dashboard_out = Command::new(bin())
        .current_dir(&fx.root)
        .env("ENVCTL_MANIFEST_DIR", &missing_manifest)
        .args(["dashboard", "--meta-file"])
        .arg(fx.meta.join(".meta.yaml"))
        .output()
        .unwrap();
    assert!(
        dashboard_out.status.success(),
        "stderr: {}",
        stderr(&dashboard_out)
    );
    assert!(stdout(&dashboard_out).contains("Generated by envctl dashboard"));
}

#[test]
fn reset_whole_roster_refuses_before_worker_and_writes_nothing() {
    let fx = Fixture::new();
    let before = tree_snapshot(&fx.root);
    let out = fx.cmd().arg("reset").output().unwrap();
    assert!(
        !out.status.success(),
        "reset without --all --confirm must fail"
    );
    assert_eq!(out.status.code(), Some(2));
    assert!(stderr(&out).contains("refusing whole-roster reset"));
    assert_eq!(
        before,
        tree_snapshot(&fx.root),
        "reset refusal mutated fixture"
    );
}

#[test]
fn lock_check_json_reports_clean_lock_as_locked_and_drift_empty() {
    let fx = Fixture::new();
    let lock = fx.cmd().arg("lock").output().unwrap();
    assert!(lock.status.success(), "stderr: {}", stderr(&lock));

    let check = fx
        .cmd()
        .args(["lock", "--check", "--json"])
        .output()
        .unwrap();
    assert!(check.status.success(), "stderr: {}", stderr(&check));
    let v: serde_json::Value = serde_json::from_slice(&check.stdout).unwrap();
    assert_eq!(
        v["locked"], true,
        "clean lock should report locked=true: {v}"
    );
    assert_eq!(v["drift"].as_array().unwrap().len(), 0, "json: {v}");
}

fn tree_snapshot(root: &Path) -> Vec<String> {
    fn walk(base: &Path, cur: &Path, out: &mut Vec<String>) {
        let mut entries: Vec<_> = std::fs::read_dir(cur)
            .unwrap()
            .map(|e| e.unwrap().path())
            .collect();
        entries.sort();
        for path in entries {
            let rel = path.strip_prefix(base).unwrap().display().to_string();
            if path.is_dir() {
                out.push(format!("dir:{rel}"));
                walk(base, &path, out);
            } else {
                let bytes = std::fs::read(&path).unwrap();
                out.push(format!("file:{rel}:{}", bytes.len()));
            }
        }
    }
    let mut out = Vec::new();
    walk(root, root, &mut out);
    out
}
