#!/usr/bin/env bash
set -euo pipefail

fail() { echo "FAIL: $*" >&2; exit 1; }

root="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"
manifest="$root/manifest/sqld.toml"
[ -f "$manifest" ] || fail "missing sqld component"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
meta="$tmp/meta"
fake_bin="$tmp/fake-bin"
shadow_bin="$tmp/compiler-shadows"
lifecycle_shadow_bin="$tmp/lifecycle-shadows"
lifecycle_shadow_marker="$tmp/lifecycle-shadow-executed"
fixture="$tmp/fixture/libsql-server-x86_64-unknown-linux-gnu"
archive="$tmp/libsql-server.tar.xz"
auth_source="$tmp/auth-source"
auth_key_source="$auth_source/auth-jwt-key.pem"
auth_token_source="$auth_source/client.jwt"
fixture_source="$tmp/envctl-source"
fixture_crate="$tmp/fixture-crate-1.0.0.crate"
auth_key_sentinel='PUBLIC-KEY-SENTINEL-NOT-A-REAL-KEY'
auth_token_sentinel='secret.jwt.token-sentinel'
mkdir -p "$meta/.config/systemd/user" "$meta/var/lib/sqld" "$fake_bin" "$shadow_bin" \
  "$lifecycle_shadow_bin" "$fixture" "$auth_source"
chmod 0700 "$meta/var/lib/sqld"
printf 'preserve durable data\n' >"$meta/var/lib/sqld/data-marker"
printf '%s\n' "$auth_key_sentinel" >"$auth_key_source"
printf '%s\n' "$auth_token_sentinel" >"$auth_token_source"
chmod 0600 "$auth_key_source" "$auth_token_source"

cat >"$fixture/sqld" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
case "${1:-}" in
  --version) echo 'sqld sqld 0.24.32 (40c272de 2025-02-14)' ;;
  --help) echo 'sqld fixture' ;;
  *) exit 0 ;;
esac
SH
chmod 755 "$fixture/sqld"
fixture_payload_sha256="$(/usr/bin/sha256sum "$fixture/sqld" | /usr/bin/awk '{print $1}')"
tar -cJf "$archive" -C "$tmp/fixture" "$(basename "$fixture")"

# Keep the Cargo provenance fixture independent of whatever registry cache happens to exist on the
# host. A one-row lock and matching synthetic `.crate` archive are sufficient because fake Cargo
# proves the staging/environment contract without compiling the workspace.
mkdir -p "$fixture_source/crates" "$fixture_source/.cargo" "$fixture_source/assets/scripts"
cp -a "$root/Cargo.toml" "$root/rust-toolchain.toml" "$fixture_source/"
cp -a "$root/crates/secretctl" "$root/crates/secrets-engine" "$root/crates/secrets-proto" \
  "$fixture_source/crates/"
cp -a "$root/.cargo/config.toml" "$fixture_source/.cargo/config.toml"
cp -a "$root/assets/scripts/envctl-sqld-hermetic-cargo.sh" \
  "$fixture_source/assets/scripts/envctl-sqld-hermetic-cargo.sh"
printf '%s\n' 'fixture crate archive bytes' >"$fixture_crate"
fixture_crate_sha256="$(/usr/bin/sha256sum "$fixture_crate" | /usr/bin/awk '{print $1}')"
cat >"$fixture_source/Cargo.lock" <<EOF
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "fixture-crate"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "$fixture_crate_sha256"
EOF

cat >"$fake_bin/curl" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
out=""
url=""
args="$*"
config_stdin=0
write_out=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    -o) out="$2"; shift 2 ;;
    --output) out="$2"; shift 2 ;;
    --write-out) write_out="$2"; shift 2 ;;
    --config) [ "$2" = - ] && config_stdin=1; shift 2 ;;
    http://*|https://*) url="$1"; shift ;;
    *) shift ;;
  esac
done
[ -n "$url" ] || exit 2
printf '%s\t%s\n' "$url" "$args" >>"${SQLD_CURL_LOG:?}"
case "$url" in
  https://github.com/*)
    [ -n "$out" ] || exit 2
    cp "${SQLD_FIXTURE_ARCHIVE:?}" "$out"
    ;;
  http://127.0.0.1:8080/v2/pipeline)
    [ "${SQLD_HEALTH_STATE:-unresponsive}" = responsive ]
    if [ "$config_stdin" = 1 ]; then
      cat >/dev/null
      exit 0
    fi
    [ "$write_out" = '%{http_code}' ] || exit 2
    if [ "${SQLD_AUTH_ENFORCED:-1}" = 1 ]; then
      printf '401'
    else
      printf '200'
    fi
    ;;
  *) exit 2 ;;
esac
SH
chmod 755 "$fake_bin/curl"

cat >"$fake_bin/sha256sum" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
if [ "${1:-}" = -c ] && [ "${2:-}" = - ]; then
  line="$(cat)"
  printf 'archive\t%s\n' "$line" >>"${SQLD_SHA_LOG:?}"
  [ "${SQLD_CHECKSUM_FAIL:-0}" = 0 ] || exit 1
  file="${line#*  }"
  [ -f "$file" ] || exit 1
  printf '%s: OK\n' "$file"
  exit 0
fi
[ "$#" = 1 ] && [ -f "$1" ] || exit 2
case "${SQLD_TEST_ARCH:-x86_64}" in
  x86_64) digest='0863c3fbe68ac9714bca2cec1330def7a0ba5e4a29f199bf60ef46fa0c95b895' ;;
  aarch64) digest='54039931c1088483706790e6cf73444ad88b843a9bb0ca8285b82fc309ad4810' ;;
  *) exit 2 ;;
esac
if grep -Fq 'same-version-tamper' "$1"; then
  digest='ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff'
fi
printf 'payload\t%s\t%s\n' "$digest" "$1" >>"${SQLD_SHA_LOG:?}"
printf '%s  %s\n' "$digest" "$1"
SH
chmod 755 "$fake_bin/sha256sum"

cat >"$fake_bin/systemctl" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >>"${SQLD_SYSTEMCTL_LOG:?}"
case " $* " in
  *' is-active '*) [ "${SQLD_SERVICE_STATE:-inactive}" = active ] ;;
  *' show --property=LoadState --value sqld.service '*)
    [ "${SQLD_SYSTEMCTL_QUERY_STATE:-ok}" = ok ] || exit 1
    printf '%s\n' "${SQLD_LOAD_STATE:-loaded}"
    ;;
  *' show --property=ActiveState --value sqld.service '*)
    [ "${SQLD_SYSTEMCTL_QUERY_STATE:-ok}" = ok ] || exit 1
    printf '%s\n' "${SQLD_ACTIVE_STATE:-${SQLD_SERVICE_STATE:-inactive}}"
    ;;
  *' show --property=MainPID --value sqld.service '*)
    [ "${SQLD_SYSTEMCTL_QUERY_STATE:-ok}" = ok ] || exit 1
    printf '%s\n' "${SQLD_MAIN_PID:-4242}"
    ;;
  *' is-enabled sqld.service '*)
    state="${SQLD_ENABLED_STATE:-enabled}"
    [ "${SQLD_LOAD_STATE:-loaded}" != not-found ] || state=not-found
    printf '%s\n' "$state"
    [ "$state" = enabled ]
    ;;
  *' restart sqld.service '*)
    [ -z "${SQLD_RESTART_MARKER:-}" ] || : >"$SQLD_RESTART_MARKER"
    [ "${SQLD_RESTART_STATE:-ok}" = ok ]
    ;;
  *' disable --now sqld.service '*) [ "${SQLD_STOP_STATE:-ok}" = ok ] ;;
  *' enable --now sqld.service '*) [ "${SQLD_RESTORE_STATE:-ok}" = ok ] ;;
  *' enable sqld.service '*) [ "${SQLD_RESTORE_STATE:-ok}" = ok ] ;;
  *' start sqld.service '*) [ "${SQLD_RESTORE_STATE:-ok}" = ok ] ;;
  *) exit 0 ;;
esac
SH
chmod 755 "$fake_bin/systemctl"

cat >"$fake_bin/rustup" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >>"__SQLD_RUSTUP_LOG__"
case "$0" in */cargo) ;; *) exit 2 ;; esac
[ "$PWD" = / ] || exit 2
rust_toolchain_dir="${0%/bin/cargo}"
case "${rust_toolchain_dir##*/}" in
  1.89.0-x86_64-unknown-linux-gnu) rust_target="x86_64-unknown-linux-gnu" ;;
  1.89.0-aarch64-unknown-linux-gnu) rust_target="aarch64-unknown-linux-gnu" ;;
  *) exit 2 ;;
esac
meta_root="${rust_toolchain_dir%/.toolchains/rustup/toolchains/*}"
llvm_bin="$meta_root/.toolchains/llvm/bin"
expected_path="$rust_toolchain_dir/bin:$llvm_bin:/usr/bin:/bin"
source_root=""
previous=""
for argument in "$@"; do
  [ "$previous" != --manifest-path ] || source_root="${argument%/Cargo.toml}"
  previous="$argument"
done
[ -n "$source_root" ] || exit 2
build_workspace="${CARGO_TARGET_DIR%/target}"
expected_cflags="--no-default-config -ffile-prefix-map=$build_workspace=/envctl-build -fdebug-prefix-map=$build_workspace=/envctl-build -ffile-prefix-map=$source_root=/envctl-source -fdebug-prefix-map=$source_root=/envctl-source -ffile-prefix-map=$meta_root=/meta -fdebug-prefix-map=$meta_root=/meta"
expected_rustflags="--remap-path-prefix=$build_workspace=/envctl-build --remap-path-prefix=$source_root=/envctl-source --remap-path-prefix=$meta_root=/meta -C link-arg=--no-default-config"
[ "$PATH" = "$expected_path" ] || exit 2
[ "${HOME:-}" = "${CARGO_TARGET_DIR%/target}/home" ] || exit 2
[ "${TMPDIR:-}" = "${CARGO_TARGET_DIR%/target}/tmp" ] || exit 2
[ "${CARGO_HOME:-}" = "${CARGO_TARGET_DIR%/target}/cargo-home" ] || exit 2
[ "${LANG:-}" = C.UTF-8 ] && [ "${LC_ALL:-}" = C.UTF-8 ] || exit 2
[ "${TZ:-}" = UTC ] && [ "${SOURCE_DATE_EPOCH:-}" = 1 ] && [ "${ZERO_AR_DATE:-}" = 1 ] || exit 2
[ "${CARGO_NET_OFFLINE:-}" = true ] && [ "${CARGO_INCREMENTAL:-}" = 0 ] || exit 2
for forbidden in LD_LIBRARY_PATH LIBRARY_PATH CPATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH \
  CCC_OVERRIDE_OPTIONS COMPILER_PATH GCC_EXEC_PREFIX RUSTC_WRAPPER RUSTC_WORKSPACE_WRAPPER; do
  [ -z "${!forbidden:-}" ] || exit 2
done
[ "${RUSTC:-}" = "$rust_toolchain_dir/bin/rustc" ] || exit 2
[ "${RUSTDOC:-}" = "$rust_toolchain_dir/bin/rustdoc" ] || exit 2
[ "${CARGO_BUILD_RUSTC:-}" = "$RUSTC" ] || exit 2
[ "${CARGO_BUILD_RUSTDOC:-}" = "$RUSTDOC" ] || exit 2
[ "${CC:-}" = "$llvm_bin/clang" ] && [ "${CXX:-}" = "$llvm_bin/clang++" ] || exit 2
[ "${AR:-}" = "$llvm_bin/llvm-ar" ] && [ "${RANLIB:-}" = "$llvm_bin/llvm-ranlib" ] || exit 2
[ "${CFLAGS:-}" = "$expected_cflags" ] && [ "${CXXFLAGS:-}" = "$expected_cflags" ] || exit 2
target_key="${rust_target//-/_}"
target_upper="${target_key^^}"
for pair in \
  "CC_${target_key}=$llvm_bin/clang" \
  "CXX_${target_key}=$llvm_bin/clang++" \
  "AR_${target_key}=$llvm_bin/llvm-ar" \
  "RANLIB_${target_key}=$llvm_bin/llvm-ranlib" \
  "CFLAGS_${target_key}=$expected_cflags" \
  "CXXFLAGS_${target_key}=$expected_cflags" \
  "CARGO_TARGET_${target_upper}_LINKER=$llvm_bin/clang"; do
  variable="${pair%%=*}"
  [ "${!variable:-}" = "${pair#*=}" ] || exit 2
done
rustflags_variable="CARGO_TARGET_${target_upper}_RUSTFLAGS"
rustflags_value="${!rustflags_variable:-}"
rustflags_prefix="$expected_rustflags -C link-arg=--ld-path="
rustflags_suffix=" -C codegen-units=1 -C embed-bitcode=yes -C lto=fat -C llvm-args=-rng-seed=1 -C link-arg=-Wl,--build-id=sha1"
case "$rustflags_value" in "$rustflags_prefix"*"$rustflags_suffix") ;; *) exit 2 ;; esac
hermetic_lld="${rustflags_value#"$rustflags_prefix"}"
hermetic_lld="${hermetic_lld%"$rustflags_suffix"}"
[ "$rustflags_value" = "$rustflags_prefix$hermetic_lld$rustflags_suffix" ] || exit 2
[ -L "$hermetic_lld" ] \
  && [ "$(readlink -f -- "$hermetic_lld")" = "$rust_toolchain_dir/lib/rustlib/$rust_target/bin/rust-lld" ] \
  || exit 2
case " $* " in
  *' --config '*) exit 2 ;;
  *' build '*--frozen*--locked*--offline*--release*' --package envctl-secretctl --bin secretctl '*) ;;
  *) exit 2 ;;
esac
registry_id=index.crates.io-1949cf8c6b5b557f
[ -f "$CARGO_HOME/registry/cache/$registry_id/fixture-crate-1.0.0.crate" ] || exit 2
[ -f "$CARGO_HOME/registry/index/$registry_id/.cache/fi/xt/fixture-crate" ] || exit 2
mkdir -p "$CARGO_HOME/registry/src/$registry_id/fixture-crate-1.0.0"
: >"$CARGO_HOME/registry/src/$registry_id/fixture-crate-1.0.0/.cargo-ok"
mkdir -p "${CARGO_TARGET_DIR:?}/release"
cat >"$CARGO_TARGET_DIR/release/secretctl" <<'HELPER'
#!/usr/bin/env bash
set -euo pipefail
file_digest() { /usr/bin/sha256sum "$1" | awk '{print $1}'; }
verify_digest_record() {
  file="$1"
  digest_file="$2"
  [ -f "$file" ] && [ ! -L "$file" ] && [ "$(stat -c '%a' "$file")" = 755 ]
  [ -f "$digest_file" ] && [ ! -L "$digest_file" ] && [ "$(stat -c '%a' "$digest_file")" = 600 ]
  IFS='  ' read -r expected recorded <"$digest_file"
  [ -n "$expected" ] && [ "$(readlink -f "$recorded")" = "$(readlink -f "$file")" ]
  [ "$(file_digest "$file")" = "$expected" ]
}
source_fingerprint() {
  source_root="$1"
  shift
  (
    cd "$source_root"
    inputs=(Cargo.toml Cargo.lock rust-toolchain.toml assets/scripts/envctl-sqld-hermetic-cargo.sh crates/secretctl crates/secrets-engine crates/secrets-proto)
    [ ! -f .cargo/config.toml ] || inputs+=(.cargo/config.toml)
    [ ! -f .cargo/config ] || inputs+=(.cargo/config)
    find "${inputs[@]}" \
      -type f \( -name '*.rs' -o -name '*.toml' -o -name '*.proto' -o -name '*.sh' -o -name Cargo.lock \) -print0 \
      | LC_ALL=C sort -z \
      | xargs -0 /usr/bin/sha256sum \
      | /usr/bin/sha256sum
    for build_input in "$@"; do
      kind="${build_input%%:*}"
      path="${build_input#?:}"
      case "$kind" in
        F|A)
          printf '%s  %s\n' "$(basename "$path")" "$(/usr/bin/sha256sum "$path" | awk '{print $1}')"
          ;;
        R)
          printf 'root:%s\n' "$(basename "$path")"
          (
            cd "$path"
            while IFS= read -r -d '' node; do
              mode="$(stat -c '%a' -- "$node")"
              if [ -L "$node" ]; then
                printf 'l\0%s\0%s\0%s\0' "${node#./}" "$mode" "$(readlink -- "$node")"
              elif [ -d "$node" ]; then
                printf 'd\0%s\0%s\0' "${node#./}" "$mode"
              elif [ -f "$node" ]; then
                printf 'f\0%s\0%s\0%s\0' "${node#./}" "$mode" \
                  "$(/usr/bin/sha256sum "$node" | awk '{print $1}')"
              else
                exit 2
              fi
            done < <(find . -mindepth 1 -print0 | LC_ALL=C sort -z)
          )
          ;;
        *) exit 2 ;;
      esac
    done | LC_ALL=C sort
  ) | /usr/bin/sha256sum | awk '{print $1}'
}
case "${1:-}" in
  internal-sqld-readiness-contract)
    shift
    [ "${1:-}" = --helper-digest ] && [ "$#" = 2 ]
    verify_digest_record "$0" "$2"
    echo 'envctl-sqld-readiness-v1'
    ;;
  internal-sqld-auth-bootstrap)
    [ -z "${SQLD_PROBE_LOG:-}" ] || printf '%s\n' "$*" >>"$SQLD_PROBE_LOG"
    shift
    public_key=""
    client_token=""
    while [ "$#" -gt 0 ]; do
      case "$1" in
        --public-key) public_key="$2"; shift 2 ;;
        --client-token) client_token="$2"; shift 2 ;;
        *) exit 2 ;;
      esac
    done
    [ -n "$public_key" ] && [ -n "$client_token" ] || exit 2
    [ ! -e "$public_key" ] && [ ! -L "$public_key" ] || exit 1
    [ ! -e "$client_token" ] && [ ! -L "$client_token" ] || exit 1
    mkdir -p "$(dirname "$public_key")" "$(dirname "$client_token")"
    printf '%s\n' '-----BEGIN PUBLIC KEY-----' 'RUST-NATIVE-BOOTSTRAP-FIXTURE' '-----END PUBLIC KEY-----' >"$public_key"
    printf '%s' 'generated.client.jwt-fixture' >"$client_token"
    chmod 0600 "$public_key" "$client_token"
    ;;
  internal-sqld-self-digest)
    shift
    output=""
    installed_path=""
    while [ "$#" -gt 0 ]; do
      case "$1" in
        --output) output="$2"; shift 2 ;;
        --installed-path) installed_path="$2"; shift 2 ;;
        *) exit 2 ;;
      esac
    done
    [ -n "$output" ] || exit 2
    [ -n "$installed_path" ] || installed_path="$0"
    [ ! -e "$output" ] && [ ! -L "$output" ] || exit 1
    umask 077
    printf '%s  %s\n' "$(/usr/bin/sha256sum "$0" | awk '{print $1}')" "$installed_path" >"$output"
    chmod 0600 "$output"
    ;;
  internal-sqld-verify-owned-digest)
    shift
    [ "${1:-}" = --file ] && file="$2" && shift 2
    [ "${1:-}" = --digest ] && digest="$2" && shift 2
    [ "$#" = 0 ]
    verify_digest_record "$file" "$digest"
    ;;
  internal-sqld-verify-current-helper)
    shift
    [ "${1:-}" = --file ] && file="$2" && shift 2
    [ "${1:-}" = --digest ] && digest="$2" && shift 2
    [ "$#" = 0 ]
    verify_digest_record "$file" "$digest"
    [ "$(file_digest "$file")" = "$(file_digest "$0")" ]
    ;;
  internal-sqld-commit-helper-generation)
    shift
    [ "${1:-}" = --staged-dir ] && staged_dir="$2" && shift 2
    [ "${1:-}" = --current-dir ] && current_dir="$2" && shift 2
    [ "$#" = 0 ] && [ "$(dirname "$0")" = "$staged_dir" ]
    for leaf in secretctl secretctl.sha256 secretctl.source.sha256; do
      [ -f "$staged_dir/$leaf" ] && [ ! -L "$staged_dir/$leaf" ]
    done
    [ "${SQLD_GENERATION_COMMIT_FAIL:-0}" = 0 ] || exit 1
    if [ -d "$current_dir" ]; then
      retired="${staged_dir}.retired"
      mv "$current_dir" "$retired"
      mv "$staged_dir" "$current_dir"
      rm -rf "$retired"
    else
      mv "$staged_dir" "$current_dir"
    fi
    ;;
  internal-sqld-source-digest)
    shift
    [ "${1:-}" = --source-root ] && source_root="$2" && shift 2
    toolchain_files=()
    toolchain_roots=()
    crate_archives=()
    while [ "${1:-}" = --toolchain-file ]; do
      toolchain_files+=("$2")
      shift 2
    done
    while [ "${1:-}" = --toolchain-root ]; do
      toolchain_roots+=("$2")
      shift 2
    done
    while [ "${1:-}" = --crate-archive ]; do
      crate_archives+=("$2")
      shift 2
    done
    [ "${1:-}" = --output ] && output="$2" && shift 2
    [ "$#" = 0 ] && [ ! -e "$output" ] && [ ! -L "$output" ]
    umask 077
    [ "${#toolchain_files[@]}" -gt 0 ] && [ "${#toolchain_roots[@]}" -gt 0 ] \
      && [ "${#crate_archives[@]}" -gt 0 ]
    fingerprint_inputs=()
    for path in "${toolchain_files[@]}"; do fingerprint_inputs+=("F:$path"); done
    for path in "${toolchain_roots[@]}"; do fingerprint_inputs+=("R:$path"); done
    for path in "${crate_archives[@]}"; do fingerprint_inputs+=("A:$path"); done
    source_fingerprint "$source_root" "${fingerprint_inputs[@]}" >"$output"
    chmod 0600 "$output"
    ;;
  internal-sqld-verify-source-digest)
    shift
    [ "${1:-}" = --source-root ] && source_root="$2" && shift 2
    toolchain_files=()
    toolchain_roots=()
    crate_archives=()
    while [ "${1:-}" = --toolchain-file ]; do
      toolchain_files+=("$2")
      shift 2
    done
    while [ "${1:-}" = --toolchain-root ]; do
      toolchain_roots+=("$2")
      shift 2
    done
    while [ "${1:-}" = --crate-archive ]; do
      crate_archives+=("$2")
      shift 2
    done
    [ "${1:-}" = --digest ] && digest="$2" && shift 2
    [ "$#" = 0 ] && [ -f "$digest" ] && [ ! -L "$digest" ] && [ "$(stat -c '%a' "$digest")" = 600 ]
    [ "${#toolchain_files[@]}" -gt 0 ] && [ "${#toolchain_roots[@]}" -gt 0 ] \
      && [ "${#crate_archives[@]}" -gt 0 ]
    fingerprint_inputs=()
    for path in "${toolchain_files[@]}"; do fingerprint_inputs+=("F:$path"); done
    for path in "${toolchain_roots[@]}"; do fingerprint_inputs+=("R:$path"); done
    for path in "${crate_archives[@]}"; do fingerprint_inputs+=("A:$path"); done
    [ "$(cat "$digest")" = "$(source_fingerprint "$source_root" "${fingerprint_inputs[@]}")" ]
    ;;
  internal-sqld-verify-sha256)
    shift
    [ "${1:-}" = --file ] && file="$2" && shift 2
    [ "${1:-}" = --expected-sha256 ] && expected="$2" && shift 2
    [ "${1:-}" = --expected-mode ] && expected_mode="$2" && shift 2
    [ "$#" = 0 ]
    [ -f "$file" ] && [ ! -L "$file" ]
    [ "0$(stat -c '%a' "$file")" = "$expected_mode" ]
    printf 'rust-verify\t%s\t%s\n' "$expected" "$file" >>"${SQLD_SHA_LOG:?}"
    [ "${SQLD_CHECKSUM_FAIL:-0}" = 0 ]
    case "$expected_mode" in
      0600) cmp -s "$file" "${SQLD_FIXTURE_ARCHIVE:?}" ;;
      0755) cmp -s "$file" "${SQLD_FIXTURE_PAYLOAD:?}" ;;
      *) exit 2 ;;
    esac
    ;;
  internal-sqld-readiness-probe)
    [ -z "${SQLD_PROBE_LOG:-}" ] || printf '%s\n' "$*" >>"$SQLD_PROBE_LOG"
    shift
    pid=""
    expected=""
    port=""
    token_file=""
    helper_digest=""
    timeout=""
    while [ "$#" -gt 0 ]; do
      case "$1" in
        --pid) pid="$2"; shift 2 ;;
        --expected-executable) expected="$2"; shift 2 ;;
        --port) port="$2"; shift 2 ;;
        --client-token) token_file="$2"; shift 2 ;;
        --helper-digest) helper_digest="$2"; shift 2 ;;
        --timeout-seconds) timeout="$2"; shift 2 ;;
        *) exit 2 ;;
      esac
    done
    [ "$pid" = "${SQLD_MAIN_PID:-4242}" ]
    [ -x "$expected" ] && [ "$port" = 8080 ] && [ -n "$timeout" ]
    [ -s "$token_file" ] && [ -s "$helper_digest" ]
    verify_digest_record "$0" "$helper_digest"
    [ "${SQLD_READY_BARRIER_STATE:-pass}" = pass ]
    [ "${SQLD_HEALTH_STATE:-responsive}" = responsive ]
    [ "${SQLD_AUTH_ENFORCED:-1}" = 1 ]
    ;;
  *) exit 2 ;;
esac
HELPER
chmod 755 "$CARGO_TARGET_DIR/release/secretctl"
SH
sed -i "s#__SQLD_RUSTUP_LOG__#$tmp/rustup.log#g" "$fake_bin/rustup"
chmod 755 "$fake_bin/rustup"

# The component invokes the META-owned rustup frontdoor by absolute path and preflights the exact
# pinned toolchain executables. Materialize deterministic regular fixtures for both supported
# architectures; ambient PATH must never be a fallback trust root.
mkdir -p "$meta/.toolchains/cargo/bin"
install -m755 "$fake_bin/rustup" "$meta/.toolchains/cargo/bin/rustup"
for rust_target in x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu; do
  toolchain_bin="$meta/.toolchains/rustup/toolchains/1.89.0-$rust_target/bin"
  rustlib_bin="$meta/.toolchains/rustup/toolchains/1.89.0-$rust_target/lib/rustlib/$rust_target/bin"
  rustlib_lib="$meta/.toolchains/rustup/toolchains/1.89.0-$rust_target/lib/rustlib/$rust_target/lib"
  mkdir -p "$toolchain_bin" "$rustlib_bin" "$rustlib_lib"
  for tool in rustc cargo rustdoc; do
    printf '%s\n' '#!/usr/bin/env bash' 'exit 99' >"$toolchain_bin/$tool"
    chmod 755 "$toolchain_bin/$tool"
  done
  install -m755 "$fake_bin/rustup" "$toolchain_bin/cargo"
  printf '%s\n' '#!/usr/bin/env bash' 'exit 99' >"$rustlib_bin/rust-lld"
  chmod 755 "$rustlib_bin/rust-lld"
  printf '%s\n' 'fixture target libstd bytes' >"$rustlib_lib/libstd-fixture.rlib"
  printf '%s\n' 'fixture rustc driver bytes' \
    >"$meta/.toolchains/rustup/toolchains/1.89.0-$rust_target/lib/librustc_driver-fixture.so"
done
mkdir -p "$meta/.toolchains/llvm/bin" "$meta/.toolchains/llvm/lib/clang/21/include"
for tool in clang clang++ llvm-ar llvm-ranlib; do
  printf '%s\n' '#!/usr/bin/env bash' 'exit 99' >"$meta/.toolchains/llvm/bin/$tool"
  chmod 755 "$meta/.toolchains/llvm/bin/$tool"
done
printf '%s\n' '#!/usr/bin/env bash' 'exit 99' >"$meta/.toolchains/llvm/bin/llvm-nm"
chmod 755 "$meta/.toolchains/llvm/bin/llvm-nm"
printf '%s\n' 'fixture complete LLVM generation record' >"$meta/.toolchains/llvm/.envctl-release"
chmod 644 "$meta/.toolchains/llvm/.envctl-release"
printf '%s\n' 'fixture libclang shared object bytes' >"$meta/.toolchains/llvm/lib/libclang.so.21.1"
ln -s libclang.so.21.1 "$meta/.toolchains/llvm/lib/libclang.so.1"
ln -s libclang.so.1 "$meta/.toolchains/llvm/lib/libclang.so"
printf '%s\n' 'typedef __SIZE_TYPE__ size_t;' \
  >"$meta/.toolchains/llvm/lib/clang/21/include/stddef.h"
registry_id=index.crates.io-1949cf8c6b5b557f
registry_cache="$meta/.toolchains/cargo/registry/cache/$registry_id"
registry_index="$meta/.toolchains/cargo/registry/index/$registry_id"
mkdir -p "$registry_cache" "$registry_index/.cache/fi/xt"
install -m644 "$fixture_crate" "$registry_cache/fixture-crate-1.0.0.crate"
printf '%s\n' '{"dl":"https://static.crates.io/crates","api":"https://crates.io"}' \
  >"$registry_index/config.json"
printf '%s\n' 'fixture sparse index entry' >"$registry_index/.cache/fi/xt/fixture-crate"
seed_meta_toolchain() {
  target_meta="$1"
  mkdir -p "$target_meta/.toolchains"
  cp -a "$meta/.toolchains/cargo" "$target_meta/.toolchains/cargo"
  cp -a "$meta/.toolchains/rustup" "$target_meta/.toolchains/rustup"
  cp -a "$meta/.toolchains/llvm" "$target_meta/.toolchains/llvm"
}

for shadow in cc gcc clang clang++ ar ranlib ld cargo rustup rustc rustdoc rust-lld; do
  cat >"$shadow_bin/$shadow" <<'SHADOW'
#!/usr/bin/env bash
set -euo pipefail
: >"${SQLD_COMPILER_SHADOW_MARKER:?}"
exit 97
SHADOW
  chmod 755 "$shadow_bin/$shadow"
done

for shadow in curl tar find install mv systemctl rm chmod mkdir cp cat grep awk sort xargs \
  uname id dirname basename env sync sha256sum mktemp readlink stat; do
  cat >"$lifecycle_shadow_bin/$shadow" <<'SHADOW'
#!/usr/bin/env bash
set -euo pipefail
: >"${SQLD_LIFECYCLE_SHADOW_MARKER:?}"
exit 96
SHADOW
  chmod 755 "$lifecycle_shadow_bin/$shadow"
done

cat >"$fake_bin/uname" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
echo "${SQLD_TEST_ARCH:-x86_64}"
SH
chmod 755 "$fake_bin/uname"

python3 - "$manifest" "$tmp" "$meta" <<'PY'
import hashlib, pathlib, sys, tomllib

data = tomllib.loads(pathlib.Path(sys.argv[1]).read_text())
component = next(c for c in data["component"] if c["id"] == "sqld")
assert component["requires"] == ["rustup", "llvm-clang"]
assert component["refresh_on_verify_failure"] is True
out = pathlib.Path(sys.argv[2])
meta = pathlib.Path(sys.argv[3])
fixture_payload_digest = hashlib.sha256(
    (out / "fixture/libsql-server-x86_64-unknown-linux-gnu/sqld").read_bytes()
).hexdigest()
for phase in ("detect", "install", "verify", "fix", "remove"):
    hook = component[phase]
    script = hook.get("script")
    if script is None:
        assert hook["command"] == "bash" and hook["args"][:1] == ["-lc"]
        script = hook["args"][1]
    # Production pins a fixed host-tool PATH. The fixture substitutes only its deterministic
    # curl/checksum/systemctl/uname doubles ahead of that same host path; caller shadows remain
    # excluded and are exercised below as tripwires.
    script = script.replace(
        "export PATH=/usr/bin:/bin",
        f"export PATH={out / 'fake-bin'}:/usr/bin:/bin",
    )
    script = script.replace(
        "0863c3fbe68ac9714bca2cec1330def7a0ba5e4a29f199bf60ef46fa0c95b895",
        fixture_payload_digest,
    ).replace(
        "54039931c1088483706790e6cf73444ad88b843a9bb0ca8285b82fc309ad4810",
        fixture_payload_digest,
    )
    script = script.replace(
        'sqld_mv() { /usr/bin/mv "$@"; }',
        '''sqld_test_mv_calls=0
sqld_mv() {
  sqld_test_mv_calls=$((sqld_test_mv_calls + 1))
  [ "${SQLD_TEST_MV_FAIL_AT:-}" != "$sqld_test_mv_calls" ] || return 1
  /usr/bin/mv "$@"
}''',
    )
    script = script.replace(
        'sqld_sync() { /usr/bin/sync "$@"; }',
        '''sqld_test_sync_calls=0
sqld_sync() {
  sqld_test_sync_calls=$((sqld_test_sync_calls + 1))
  [ "${SQLD_TEST_SYNC_FAIL_AT:-}" != "$sqld_test_sync_calls" ] || return 1
  /usr/bin/sync "$@"
}''',
    )
    script = script.replace(
        'sqld_remove_mv() { /usr/bin/mv "$@"; }',
        '''sqld_test_remove_mv_calls=0
sqld_remove_mv() {
  sqld_test_remove_mv_calls=$((sqld_test_remove_mv_calls + 1))
  [ "${SQLD_TEST_REMOVE_MV_FAIL_AT:-}" != "$sqld_test_remove_mv_calls" ] || return 1
  /usr/bin/mv "$@"
}''',
    )
    script = script.replace(
        'sqld_remove_sync() { /usr/bin/sync "$@"; }',
        '''sqld_test_remove_sync_calls=0
sqld_remove_sync() {
  sqld_test_remove_sync_calls=$((sqld_test_remove_sync_calls + 1))
  [ "${SQLD_TEST_REMOVE_SYNC_FAIL_AT:-}" != "$sqld_test_remove_sync_calls" ] || return 1
  /usr/bin/sync "$@"
}''',
    )
    script = script.replace(
        'sqld_remove_mktemp() { /usr/bin/mktemp "$@"; }',
        '''sqld_remove_mktemp() {
  [ "${SQLD_TEST_REMOVE_MKTEMP_FAIL:-0}" = 0 ] || return 1
  /usr/bin/mktemp "$@"
}''',
    )
    path = out / f"{phase}.sh"
    path.write_text(script)
    path.chmod(0o755)

unit = next(u for u in component["wiring"]["systemd_user"] if u["name"] == "sqld.service")
content = unit["content"]
assert 'Environment="META_ROOT=${META_ROOT}"' in content
assert 'ExecStart="${META_ROOT}/usr/bin/sqld" --http-listen-addr 127.0.0.1:8080 --auth-jwt-key-file "${META_ROOT}/.config/sqld/auth-jwt-key.pem" -d "${META_ROOT}/var/lib/sqld"' in content
assert 'Type=exec' in content
assert 'ExecStartPost=/usr/bin/sha256sum' not in content
assert '/usr/bin/sha256sum' not in content
assert """ExecStartPost=/bin/sh -c 'pid=\"$(systemctl --user show --property=MainPID --value sqld.service)\"; case \"$pid\" in \"\"|0|*[!0-9]*) exit 1 ;; esac; exec \"${META_ROOT}/usr/libexec/envctl/sqld/bin/current/secretctl\" internal-sqld-readiness-probe --pid \"$pid\" --expected-executable \"${META_ROOT}/.toolchains/sqld/bin/sqld\" --port 8080 --client-token \"${META_ROOT}/.config/sqld/client.jwt\" --helper-digest \"${META_ROOT}/usr/libexec/envctl/sqld/bin/current/secretctl.sha256\" --timeout-seconds 20'""" in content
assert 'TimeoutStartSec=30' in content
assert 'LimitCORE=0' in content
assert 'ReadOnlyPaths="${META_ROOT}/.config/sqld/auth-jwt-key.pem" "${META_ROOT}/.config/sqld/client.jwt"' in content
assert 'ReadWritePaths="${META_ROOT}/var/lib/sqld"' in content
assert "0.0.0.0" not in content and "%h/Desktop/meta" not in content and "/home/" not in content
assert component["wiring"]["data_paths"] == [{"path": "$META_ROOT/var/lib/sqld", "uuid": "runtime"}]
assert component["wiring"]["config_paths"] == [{"path": "$META_ROOT/.config/sqld"}]
assert "internal-sqld-auth-bootstrap" in component["install"]["script"]
assert "internal-sqld-auth-bootstrap" in component["fix"]["script"]
assert "load_hermetic_cargo_helpers" in component["install"]["script"]
assert "stage_hermetic_cargo_home" in component["install"]["script"]
assert "run_hermetic_cargo_build" in component["install"]["script"]
assert "collect_used_crate_archives" in component["install"]["script"]
assert "internal-sqld-readiness-contract" in component["install"]["script"]
assert "helper_owned_or_absent" in component["install"]["script"]
assert "internal-sqld-self-digest" in component["install"]["script"]
assert "internal-sqld-verify-current-helper" in component["install"]["script"]
assert 'sqld_mv -T --exchange --no-copy -- "$stage_dir" "$probe_dir"' in component["install"]["script"]
assert "rollback_helper_activation" in component["install"]["script"]
assert 'mv -f "$staged_probe" "$probe"' not in component["install"]["script"]
assert 'mv -f "$staged_digest" "$probe_digest"' not in component["install"]["script"]
assert "reject_external_build_config" in component["install"]["script"]
assert "CARGO_TARGET_*_LINKER" in component["install"]["script"]
assert '--toolchain-root "$clang_resource_root"' in component["install"]["script"]
assert '--toolchain-root "$rust_toolchain_lib_root"' in component["install"]["script"]
assert '--toolchain-root "$llvm_generation_root"' in component["install"]["script"]
assert '"${crate_archive_args[@]}"' in component["install"]["script"]
assert "secretctl.source.sha256" in component["install"]["script"]
assert "revalidate_active_service" in component["install"]["script"]
assert "revalidate_active_service" in component["fix"]["script"]
detect_script = component["detect"]["args"][1]
assert "internal-sqld-" not in detect_script
assert "--version" not in detect_script
assert "run_hermetic_cargo_build" in component["verify"]["args"][1]
assert "internal-sqld-verify-current-helper" in component["verify"]["args"][1]
(meta / ".config/systemd/user/sqld.service").write_text(content.replace("${META_ROOT}", str(meta)))
PY

export META_ROOT="$meta"
export PATH="$shadow_bin:$fake_bin:/usr/bin:/bin"
export SQLD_FIXTURE_ARCHIVE="$archive"
export SQLD_FIXTURE_PAYLOAD="$fixture/sqld"
export SQLD_CURL_LOG="$tmp/curl.log"
export SQLD_SHA_LOG="$tmp/sha.log"
export SQLD_SYSTEMCTL_LOG="$tmp/systemctl.log"
export SQLD_RUSTUP_LOG="$tmp/rustup.log"
export SQLD_PROBE_LOG="$tmp/probe.log"
export SQLD_COMPILER_SHADOW_MARKER="$tmp/compiler-shadow-executed"
export SQLD_LIFECYCLE_SHADOW_MARKER="$lifecycle_shadow_marker"
export ENVCTL_SOURCE_ROOT="$fixture_source"
export SQLD_AUTH_JWT_KEY_SOURCE="$auth_key_source"
export SQLD_CLIENT_JWT_SOURCE="$auth_token_source"
touch "$SQLD_CURL_LOG" "$SQLD_SHA_LOG" "$SQLD_SYSTEMCTL_LOG" "$SQLD_RUSTUP_LOG" "$SQLD_PROBE_LOG"
download_count() { grep -c '^https://github.com/' "$SQLD_CURL_LOG" || true; }

if bash "$tmp/detect.sh"; then fail "detect passed before install"; fi

# A regular executable can spoof the semantic contract string. Without the component's owned-byte
# digest it is foreign and must be refused BEFORE it can run or receive the token-file path.
meta_spoof="$tmp/meta-spoof"
spoof_probe="$meta_spoof/usr/libexec/envctl/sqld/bin/current/secretctl"
spoof_marker="$tmp/spoof-was-executed"
mkdir -p "$(dirname "$spoof_probe")" "$meta_spoof/var/lib/sqld"
chmod 0700 "$meta_spoof/var/lib/sqld"
seed_meta_toolchain "$meta_spoof"
cat >"$spoof_probe" <<'SH'
#!/usr/bin/env bash
touch "${SQLD_SPOOF_MARKER:?}"
echo 'envctl-sqld-readiness-v1'
SH
chmod 755 "$spoof_probe"
export META_ROOT="$meta_spoof"
export SQLD_SPOOF_MARKER="$spoof_marker"
spoof_builds_before="$(wc -l <"$SQLD_RUSTUP_LOG")"
if bash "$tmp/install.sh"; then fail "install trusted a self-attesting foreign readiness helper"; fi
[ ! -e "$spoof_marker" ] || fail "foreign readiness helper executed before owned-byte validation"
[ "$(wc -l <"$SQLD_RUSTUP_LOG")" = "$spoof_builds_before" ] \
  || fail "foreign readiness-helper refusal started a Rust build"
[ ! -e "$meta_spoof/.config/sqld/client.jwt" ] \
  || fail "foreign readiness helper received or caused credential creation"
unset SQLD_SPOOF_MARKER
export META_ROOT="$meta"

# Source-root and managed-parent containment are preflighted before Cargo or any destination write.
source_link="$tmp/envctl-source-link"
ln -s "$fixture_source" "$source_link"
export ENVCTL_SOURCE_ROOT="$source_link"
containment_builds_before="$(wc -l <"$SQLD_RUSTUP_LOG")"
if bash "$tmp/install.sh"; then fail "install accepted a symlinked envctl source root"; fi
[ "$(wc -l <"$SQLD_RUSTUP_LOG")" = "$containment_builds_before" ] \
  || fail "symlinked source root reached Cargo"
[ ! -e "$meta/.toolchains/sqld/bin/sqld" ] && [ ! -e "$meta/usr/libexec/envctl/sqld/bin/current" ] \
  || fail "symlinked source-root refusal mutated managed install state"
export ENVCTL_SOURCE_ROOT="$fixture_source"

meta_parent_link="$tmp/meta-parent-link"
outside_parent="$tmp/outside-parent"
mkdir -p "$meta_parent_link" "$outside_parent"
seed_meta_toolchain "$meta_parent_link"
printf 'outside sentinel\n' >"$outside_parent/sentinel"
ln -s "$outside_parent" "$meta_parent_link/usr"
export META_ROOT="$meta_parent_link"
if bash "$tmp/install.sh"; then fail "install accepted a symlinked managed parent"; fi
[ "$(cat "$outside_parent/sentinel")" = 'outside sentinel' ] \
  || fail "managed-parent refusal mutated the outside target"
[ -z "$(find "$outside_parent" -mindepth 1 ! -name sentinel -print -quit)" ] \
  || fail "managed-parent refusal wrote through the outside symlink"
export META_ROOT="$meta"

# Cargo runs from `/` with a fresh private CARGO_HOME. Both ancestor and checked-in configs remain
# authenticated source bytes, but neither is executable compiler configuration for the GNU build.
source_parent="$tmp/injected-source-parent"
source_copy="$source_parent/source"
mkdir -p "$source_copy/crates" "$source_copy/.cargo" "$source_parent/.cargo"
cp -a "$fixture_source/Cargo.toml" "$fixture_source/Cargo.lock" "$fixture_source/rust-toolchain.toml" "$source_copy/"
cp -a "$fixture_source/crates/secretctl" "$fixture_source/crates/secrets-engine" \
  "$fixture_source/crates/secrets-proto" "$source_copy/crates/"
cp -a "$fixture_source/assets" "$source_copy/assets"
cp -a "$fixture_source/.cargo/config.toml" "$source_copy/.cargo/config.toml"
ambient_config_marker="$tmp/ambient-config-executed"
printf '%s\n' '#!/usr/bin/env bash' ": >\"$ambient_config_marker\"" >"$tmp/ambient-config-wrapper"
chmod 0755 "$tmp/ambient-config-wrapper"
printf '%s\n' '[build]' "rustc-wrapper = \"$tmp/ambient-config-wrapper\"" >"$source_parent/.cargo/config.toml"
printf '%s\n' '[build]' "rustc-wrapper = \"$tmp/ambient-config-wrapper\"" >"$source_copy/.cargo/config.toml"
meta_ancestor_config="$tmp/meta-ancestor-config"
mkdir -p "$meta_ancestor_config/var/lib/sqld"
chmod 0700 "$meta_ancestor_config/var/lib/sqld"
seed_meta_toolchain "$meta_ancestor_config"
export META_ROOT="$meta_ancestor_config"
export ENVCTL_SOURCE_ROOT="$source_copy"
config_builds_before="$(wc -l <"$SQLD_RUSTUP_LOG")"
bash "$tmp/install.sh"
[ "$(wc -l <"$SQLD_RUSTUP_LOG")" = "$((config_builds_before + 1))" ] \
  || fail "neutral-cwd helper build did not run exactly once"
[ ! -e "$ambient_config_marker" ] || fail "ancestor or checked-in Cargo config influenced the build"
if grep -Fq -- '--config' "$SQLD_RUSTUP_LOG"; then
  fail "checked-in Cargo config was executed instead of remaining fingerprint-only input"
fi
export ENVCTL_SOURCE_ROOT="$fixture_source"
export META_ROOT="$meta"

meta_cargo_config="$tmp/meta-cargo-config"
mkdir -p "$meta_cargo_config"
seed_meta_toolchain "$meta_cargo_config"
printf '%s\n' '[build]' 'rustc-wrapper = "/must/not/execute"' >"$meta_cargo_config/.toolchains/cargo/config.toml"
export META_ROOT="$meta_cargo_config"
cargo_home_builds_before="$(wc -l <"$SQLD_RUSTUP_LOG")"
if bash "$tmp/install.sh"; then fail "install accepted an ambient CARGO_HOME config"; fi
[ "$(wc -l <"$SQLD_RUSTUP_LOG")" = "$cargo_home_builds_before" ] \
  || fail "ambient CARGO_HOME config reached rustup"

# Environment-based compiler/linker injection is cleared before the absolute META-owned rustup
# frontdoor is called. The fake rustup executes any surviving injection variable as a tripwire.
meta_env_injection="$tmp/meta-env-injection"
mkdir -p "$meta_env_injection/var/lib/sqld"
chmod 0700 "$meta_env_injection/var/lib/sqld"
seed_meta_toolchain "$meta_env_injection"
injection_marker="$tmp/compiler-injection-executed"
cat >"$tmp/compiler-injector" <<SH
#!/usr/bin/env bash
: >"$injection_marker"
SH
chmod 0755 "$tmp/compiler-injector"
export META_ROOT="$meta_env_injection"
export RUSTC_WRAPPER="$tmp/compiler-injector"
export CC="$tmp/compiler-injector"
export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER="$tmp/compiler-injector"
export LD_LIBRARY_PATH="$tmp" LIBRARY_PATH="$tmp" CPATH="$tmp" C_INCLUDE_PATH="$tmp"
export CPLUS_INCLUDE_PATH="$tmp" CCC_OVERRIDE_OPTIONS="#^$tmp/compiler-injector"
export COMPILER_PATH="$tmp" GCC_EXEC_PREFIX="$tmp"
original_home="$HOME"
export HOME="$tmp/hostile-home"
mkdir -p "$HOME/.config/clang"
printf '%s\n' '--config-system-dir=/must/not/use' >"$HOME/.config/clang/x86_64-unknown-linux-gnu.cfg"
bash "$tmp/install.sh"
[ ! -e "$injection_marker" ] || fail "compiler/linker environment injection executed"
unset RUSTC_WRAPPER CC CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER \
  LD_LIBRARY_PATH LIBRARY_PATH CPATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH CCC_OVERRIDE_OPTIONS \
  COMPILER_PATH GCC_EXEC_PREFIX HOME
export HOME="$original_home"
export META_ROOT="$meta"

chmod 0644 "$auth_token_source"
if bash "$tmp/install.sh"; then fail "install accepted a group-readable JWT source"; fi
chmod 0600 "$auth_token_source"
[ ! -e "$meta/.config/sqld/client.jwt" ] || fail "unsafe JWT source was copied"

export SQLD_CHECKSUM_FAIL=1
if bash "$tmp/install.sh"; then fail "install accepted a checksum mismatch"; fi
unset SQLD_CHECKSUM_FAIL
[ ! -e "$meta/.toolchains/sqld/bin/sqld" ] || fail "checksum failure installed a payload"
[ ! -e "$meta/usr/bin/sqld" ] || fail "checksum failure installed a frontdoor"

bash "$tmp/install.sh"
bash "$tmp/detect.sh"

# Caller PATH is adversarial input. Every lifecycle phase replaces it with the fixed host-tool
# path before resolving utilities, so even an idempotent install/detect cannot execute shadows.
PATH="$lifecycle_shadow_bin:$PATH" bash "$tmp/install.sh"
PATH="$lifecycle_shadow_bin:$PATH" bash "$tmp/detect.sh"
[ ! -e "$lifecycle_shadow_marker" ] || fail "sqld lifecycle executed a caller PATH shadow"

# A failure immediately before the generation commit must leave the complete old current triple
# untouched; the abandoned staged directory is removed by the hook trap, and a retry converges.
current_dir="$meta/usr/libexec/envctl/sqld/bin/current"
generation_before="$(/usr/bin/sha256sum "$current_dir/secretctl" "$current_dir/secretctl.sha256" "$current_dir/secretctl.source.sha256")"
export SQLD_TEST_MV_FAIL_AT=1
if bash "$tmp/install.sh"; then fail "injected helper-generation commit failure was ignored"; fi
unset SQLD_TEST_MV_FAIL_AT
[ "$(/usr/bin/sha256sum "$current_dir/secretctl" "$current_dir/secretctl.sha256" "$current_dir/secretctl.source.sha256")" = "$generation_before" ] \
  || fail "failed helper-generation commit changed the active triple"
[ -z "$(find "$meta/usr/libexec/envctl/sqld/bin" -maxdepth 1 -name '.next.*' -print -quit)" ] \
  || fail "failed helper-generation commit leaked a staged directory"
bash "$tmp/install.sh"

export SQLD_SERVICE_STATE=inactive
export SQLD_HEALTH_STATE=responsive
if bash "$tmp/verify.sh"; then fail "verify accepted an inactive sqld service"; fi
export SQLD_SERVICE_STATE=active
export SQLD_HEALTH_STATE=unresponsive
if bash "$tmp/verify.sh"; then fail "verify accepted an unresponsive sqld service"; fi
export SQLD_HEALTH_STATE=responsive
export SQLD_AUTH_ENFORCED=0
if bash "$tmp/verify.sh"; then fail "verify accepted an open-auth sqld service"; fi
export SQLD_AUTH_ENFORCED=1
bash "$tmp/verify.sh"

private="$meta/.toolchains/sqld/bin/sqld"
front="$meta/usr/bin/sqld"
managed_key="$meta/.config/sqld/auth-jwt-key.pem"
managed_token="$meta/.config/sqld/client.jwt"
managed_probe="$meta/usr/libexec/envctl/sqld/bin/current/secretctl"
managed_probe_digest="$meta/usr/libexec/envctl/sqld/bin/current/secretctl.sha256"
managed_probe_source="$meta/usr/libexec/envctl/sqld/bin/current/secretctl.source.sha256"
[ -x "$private" ] && [ ! -L "$private" ] || fail "private sqld payload missing"
[ -x "$front" ] && [ ! -L "$front" ] || fail "sqld frontdoor is not a regular executable"
[ -f "$managed_key" ] && [ ! -L "$managed_key" ] || fail "managed JWT verification key missing"
[ -f "$managed_token" ] && [ ! -L "$managed_token" ] || fail "managed client JWT missing"
[ -x "$managed_probe" ] && [ ! -L "$managed_probe" ] || fail "managed Rust readiness helper missing"
[ -f "$managed_probe_digest" ] && [ ! -L "$managed_probe_digest" ] \
  || fail "managed Rust readiness-helper digest missing"
[ "$(stat -c '%a' "$managed_probe_digest")" = 600 ] \
  || fail "managed Rust readiness-helper digest is not 0600"
[ -f "$managed_probe_source" ] && [ ! -L "$managed_probe_source" ] \
  || fail "managed Rust readiness-helper source identity missing"
[ "$(stat -c '%a' "$managed_probe_source")" = 600 ] \
  || fail "managed Rust readiness-helper source identity is not 0600"
managed_source_identity="$(cat "$managed_probe_source")"
case "$managed_source_identity" in ''|*[!0-9a-f]*) fail "managed Rust readiness-helper source identity is malformed" ;; esac
[ "${#managed_source_identity}" = 64 ] \
  || fail "managed Rust readiness-helper source identity is not 64 characters"
/usr/bin/sha256sum --check --status "$managed_probe_digest" \
  || fail "managed Rust readiness helper does not match its owned-byte digest"
[ "$($managed_probe internal-sqld-readiness-contract --helper-digest "$managed_probe_digest")" = 'envctl-sqld-readiness-v1' ] \
  || fail "managed Rust readiness helper has the wrong contract"
[ "$(stat -c '%a' "$managed_key")" = 600 ] || fail "managed JWT verification key is not 0600"
[ "$(stat -c '%a' "$managed_token")" = 600 ] || fail "managed client JWT is not 0600"
[ "$(cat "$managed_key")" = "$auth_key_sentinel" ] || fail "managed JWT key differs from source"
[ "$(cat "$managed_token")" = "$auth_token_sentinel" ] || fail "managed client JWT differs from source"
grep -Fqx '# managed-by: envctl component sqld' "$front" || fail "frontdoor marker missing"
grep -Fqx "exec \"$private\" \"\$@\"" "$front" || fail "frontdoor target mismatch"
[ "$($front --version)" = 'sqld sqld 0.24.32 (40c272de 2025-02-14)' ] \
  || fail "installed sqld version is not the pinned build"
grep -Fq 'libsql-server-v0.24.32/libsql-server-x86_64-unknown-linux-gnu.tar.xz' "$SQLD_CURL_LOG" \
  || fail "x86_64 release URL is not pinned to v0.24.32"
grep -Fq '71720fc8648c19efef416efebd47145ef59b62e198770533530a858e1336879f' "$SQLD_SHA_LOG" \
  || fail "x86_64 release checksum was not verified"
grep -Fq "$fixture_payload_sha256" "$SQLD_SHA_LOG" \
  || fail "installed x86_64 payload digest was not verified"
[ -f "$meta/var/lib/sqld/data-marker" ] || fail "install deleted durable data"
if grep -R -Fq "$auth_token_sentinel" "$SQLD_CURL_LOG" "$SQLD_SYSTEMCTL_LOG" \
  "$SQLD_RUSTUP_LOG" "$SQLD_PROBE_LOG" "$manifest" "$meta/.config/systemd/user/sqld.service"; then
  fail "client JWT leaked into argv, logs, manifest, or systemd unit"
fi

# The source identity covers all META-owned compiler data, not only executable entrypoints. Host
# Ubuntu headers/CRT/runtime libraries are a documented residual outside this digest. Mutating a
# Rust library or non-entrypoint LLVM file must make Verify stale; restoring bytes restores it.
rust_closure_input="$meta/.toolchains/rustup/toolchains/1.89.0-x86_64-unknown-linux-gnu/lib/librustc_driver-fixture.so"
llvm_closure_input="$meta/.toolchains/llvm/bin/llvm-nm"
cp "$rust_closure_input" "$tmp/rust-closure-input"
printf '%s\n' 'compiler closure drift' >>"$rust_closure_input"
if bash "$tmp/verify.sh"; then fail "Verify ignored Rust compiler-library drift"; fi
cp "$tmp/rust-closure-input" "$rust_closure_input"
bash "$tmp/verify.sh"
cp "$llvm_closure_input" "$tmp/llvm-closure-input"
printf '%s\n' 'LLVM closure drift' >>"$llvm_closure_input"
if bash "$tmp/verify.sh"; then fail "Verify ignored non-entrypoint LLVM drift"; fi
cp "$tmp/llvm-closure-input" "$llvm_closure_input"
bash "$tmp/verify.sh"

printf '%s\n' 'outside compiler bytes' >"$tmp/outside-compiler-input"
ln -s ../../../../outside-compiler-input "$meta/.toolchains/llvm/bin/escaping-link"
if bash "$tmp/verify.sh"; then fail "Verify accepted an escaping LLVM symlink"; fi
rm -f "$meta/.toolchains/llvm/bin/escaping-link"
ln -s missing-target "$meta/.toolchains/llvm/bin/dangling-link"
if bash "$tmp/verify.sh"; then fail "Verify accepted a dangling LLVM symlink"; fi
rm -f "$meta/.toolchains/llvm/bin/dangling-link"
bash "$tmp/verify.sh"

# Even shell xtrace may expose only the credential path: Verify delegates exact MainPID/auth proof
# to the helper and never reads the bearer into a shell variable or curl configuration.
bash -x "$tmp/verify.sh" >/dev/null 2>"$tmp/verify.trace"
if grep -Fq "$auth_token_sentinel" "$tmp/verify.trace"; then
  fail "verify xtrace exposed the sqld client JWT"
fi

# Full forged-triple lifecycle: a foreign helper can pair its own bytes with a matching path-bound
# digest and a plausible source record. Physical Detect must pass without executing it; the fresh
# isolated current-source verifier must reject it without handing it the token path; the refresh
# Install path then replaces it, and the post-install Verify succeeds on current bytes.
forged_marker="$tmp/forged-helper-executed"
cat >"$managed_probe" <<SH
#!/usr/bin/env bash
: >"$forged_marker"
if [ "\${1:-}" = internal-sqld-readiness-contract ]; then
  echo envctl-sqld-readiness-v1
fi
exit 0
SH
chmod 0755 "$managed_probe"
printf '%s  %s\n' "$(/usr/bin/sha256sum "$managed_probe" | awk '{print $1}')" "$managed_probe" \
  >"$managed_probe_digest"
chmod 0600 "$managed_probe_digest"
printf '%s\n' "$managed_source_identity" >"$managed_probe_source"
chmod 0600 "$managed_probe_source"
bash "$tmp/detect.sh" || fail "physical Detect rejected a complete forged helper triple"
[ ! -e "$forged_marker" ] || fail "physical Detect executed the forged helper"
if bash "$tmp/verify.sh"; then fail "fresh verifier accepted a forged helper triple"; fi
[ ! -e "$forged_marker" ] || fail "Verify executed the forged helper or exposed its token path"
bash "$tmp/install.sh"
[ ! -e "$forged_marker" ] || fail "refresh Install executed the forged incumbent helper"
bash "$tmp/verify.sh"

# If the replacement barrier and synchronous restart both fail, the complete helper generation
# is restored before the previously active/enabled service is brought back. A later retry repairs
# the intentionally stale source record and converges.
printf '%064d\n' 0 >"$managed_probe_source"
restart_failure_hash="$(/usr/bin/sha256sum "$private" "$front" "$managed_probe" "$managed_probe_digest" "$managed_probe_source")"
restores_before="$(grep -Fc -- '--user enable --now sqld.service' "$SQLD_SYSTEMCTL_LOG" || true)"
export SQLD_READY_BARRIER_STATE=fail SQLD_RESTART_STATE=fail
if bash "$tmp/install.sh"; then fail "install ignored a failed replacement-helper restart"; fi
unset SQLD_READY_BARRIER_STATE SQLD_RESTART_STATE
[ "$(/usr/bin/sha256sum "$private" "$front" "$managed_probe" "$managed_probe_digest" "$managed_probe_source")" = "$restart_failure_hash" ] \
  || fail "failed replacement-helper restart did not restore incumbent runtime bytes"
[ "$(grep -Fc -- '--user enable --now sqld.service' "$SQLD_SYSTEMCTL_LOG" || true)" = "$((restores_before + 1))" ] \
  || fail "failed replacement-helper restart did not restore active/enabled service state"
bash "$tmp/install.sh"
bash "$tmp/verify.sh"
[ ! -e "$forged_marker" ] || fail "post-install Verify executed the replaced forged helper"
[ "$(/usr/bin/sha256sum "$managed_probe" | awk '{print $1}')" != \
  "$(printf '%s\n' '#!/usr/bin/env bash' ': forged' | /usr/bin/sha256sum | awk '{print $1}')" ] \
  || fail "forged helper replacement fixture was inconclusive"

# Detect is deliberately physical; a stale checked-in-source fingerprint is Verify drift. Repair
# rebuilds the helper, then an already-current active unit must execute the replacement barrier. A
# failed direct proof forces a synchronous restart (whose real ExecStartPost is the same barrier).
printf '%064d\n' 0 >"$managed_probe_source"
chmod 0600 "$managed_probe_source"
bash "$tmp/detect.sh" || fail "detect rejected a physically safe helper with stale source identity"
if bash "$tmp/verify.sh"; then fail "verify accepted stale readiness-helper source inputs"; fi
readiness_calls_before="$(grep -c '^internal-sqld-readiness-probe ' "$SQLD_PROBE_LOG" || true)"
restart_marker="$tmp/sqld-restarted-after-helper-upgrade"
export SQLD_READY_BARRIER_STATE=fail
export SQLD_RESTART_MARKER="$restart_marker"
bash "$tmp/install.sh"
unset SQLD_READY_BARRIER_STATE SQLD_RESTART_MARKER
[ "$(cat "$managed_probe_source")" = "$managed_source_identity" ] \
  || fail "helper repair did not restore the current source identity"
[ -f "$restart_marker" ] || fail "failed replacement-helper proof did not restart active sqld"
[ "$(grep -c '^internal-sqld-readiness-probe ' "$SQLD_PROBE_LOG" || true)" = "$((readiness_calls_before + 1))" ] \
  || fail "active current unit did not execute the replacement readiness helper exactly once"
grep -Fqx -- '--user restart sqld.service' "$SQLD_SYSTEMCTL_LOG" \
  || fail "active helper-upgrade fallback did not synchronously restart sqld.service"
bash "$tmp/verify.sh"

first_hash="$(/usr/bin/sha256sum "$private" "$front" "$managed_key" "$managed_token" "$managed_probe" "$managed_probe_digest" "$managed_probe_source")"
downloads="$(download_count)"
idempotent_builds_before="$(wc -l <"$SQLD_RUSTUP_LOG")"
idempotent_enables_before="$(grep -Fc -- '--user enable --now sqld.service' "$SQLD_SYSTEMCTL_LOG" || true)"
bash "$tmp/install.sh"
bash "$tmp/fix.sh"
[ "$(/usr/bin/sha256sum "$private" "$front" "$managed_key" "$managed_token" "$managed_probe" "$managed_probe_digest" "$managed_probe_source")" = "$first_hash" ] \
  || fail "install/fix is not idempotent or rewrote auth materials"
[ "$(wc -l <"$SQLD_RUSTUP_LOG")" = "$((idempotent_builds_before + 2))" ] \
  || fail "install/fix did not rebuild the owned readiness helper for security upgrades"
[ "$(download_count)" = "$downloads" ] || fail "idempotent install/fix downloaded again"
if [ "$(grep -Fc -- '--user enable --now sqld.service' "$SQLD_SYSTEMCTL_LOG" || true)" != \
  "$idempotent_enables_before" ]; then
  fail "fix started sqld before the engine wiring phase owned the unit"
fi

# An older *owned* helper has a matching digest but may share the same contract string. Every
# install/fix must rebuild and atomically replace it so security changes cannot remain stale.
current_probe_hash="$(/usr/bin/sha256sum "$managed_probe" | awk '{print $1}')"
cat >"$managed_probe" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = internal-sqld-readiness-contract ]; then
  echo 'envctl-sqld-readiness-v1'
  exit 0
fi
exit 77
SH
chmod 755 "$managed_probe"
/usr/bin/sha256sum "$managed_probe" >"$managed_probe_digest"
chmod 0600 "$managed_probe_digest"
stale_probe_hash="$(/usr/bin/sha256sum "$managed_probe" | awk '{print $1}')"
[ "$stale_probe_hash" != "$current_probe_hash" ] || fail "stale-helper fixture did not differ"
upgrade_builds_before="$(wc -l <"$SQLD_RUSTUP_LOG")"
bash "$tmp/install.sh"
[ "$(wc -l <"$SQLD_RUSTUP_LOG")" = "$((upgrade_builds_before + 1))" ] \
  || fail "owned stale helper was not rebuilt exactly once"
[ "$(/usr/bin/sha256sum "$managed_probe" | awk '{print $1}')" = "$current_probe_hash" ] \
  || fail "owned stale helper survived the upgrade install"
/usr/bin/sha256sum --check --status "$managed_probe_digest" \
  || fail "upgraded helper digest does not bind the replaced bytes"

# A full safe helper triple that fails fresh equality is refreshable. Install builds in a new
# run-private target, never executes the stale incumbent, and exchanges the complete generation.
printf '\n# tampered after install\n' >>"$managed_probe"
tamper_builds_before="$(wc -l <"$SQLD_RUSTUP_LOG")"
bash "$tmp/install.sh"
[ "$(wc -l <"$SQLD_RUSTUP_LOG")" = "$((tamper_builds_before + 1))" ] \
  || fail "tampered-helper refresh did not perform exactly one private build"
[ "$(stat -c '%a' "$managed_probe")" = 755 ] || fail "refreshed helper mode changed"
[ "$(/usr/bin/sha256sum "$managed_probe" | awk '{print $1}')" = "$current_probe_hash" ] \
  || fail "tampered incumbent was not replaced by fresh bytes"

payload_marker="$tmp/tampered-payload-executed"
cat >"$private" <<SH
#!/usr/bin/env bash
# same-version-tamper
: >"$payload_marker"
echo 'sqld sqld 0.24.32 (40c272de 2025-02-14)'
SH
chmod 755 "$private"
bash "$tmp/detect.sh" || fail "physical Detect rejected a regular tampered payload"
[ ! -e "$payload_marker" ] || fail "Detect executed an unauthenticated payload"
if bash "$tmp/verify.sh"; then fail "verify accepted a same-version tampered payload"; fi
[ ! -e "$payload_marker" ] || fail "Verify executed an unauthenticated payload"
bash "$tmp/fix.sh"
[ ! -e "$payload_marker" ] || fail "Fix executed an unauthenticated incumbent payload"
[ "$(download_count)" = "$((downloads + 1))" ] || fail "same-version tamper fix did not fetch once"
downloads="$((downloads + 1))"

cat >"$private" <<'SH'
#!/usr/bin/env bash
echo 'sqld sqld 0.24.31 (old build)'
SH
chmod 755 "$private"
bash "$tmp/detect.sh" || fail "physical Detect rejected a regular wrong-byte payload"
if bash "$tmp/verify.sh"; then fail "verify accepted a wrong sqld version"; fi
bash "$tmp/fix.sh"
[ "$($private --version)" = 'sqld sqld 0.24.32 (40c272de 2025-02-14)' ] \
  || fail "fix did not replace the wrong sqld version"
[ "$(download_count)" = "$((downloads + 1))" ] || fail "wrong-version fix did not fetch once"
[ -f "$meta/var/lib/sqld/data-marker" ] || fail "fix deleted durable data"
downloads="$((downloads + 1))"

# Exact pinned bytes are still rejected through a symlink, and special mode bits are not masked
# away. Neither unsafe representation may reach execution or readiness.
mv "$private" "$private.exact-bytes"
ln -s "$private.exact-bytes" "$private"
if bash "$tmp/detect.sh"; then fail "Detect accepted an exact-digest payload symlink"; fi
if bash "$tmp/verify.sh"; then fail "Verify accepted an exact-digest payload symlink"; fi
symlink_target_hash="$(/usr/bin/sha256sum "$private.exact-bytes" | awk '{print $1}')"
if bash "$tmp/fix.sh"; then fail "Fix accepted an exact-digest payload symlink"; fi
[ -L "$private" ] || fail "failed-closed Fix mutated the payload symlink"
[ "$(/usr/bin/sha256sum "$private.exact-bytes" | awk '{print $1}')" = "$symlink_target_hash" ] \
  || fail "failed-closed Fix mutated through the payload symlink"
[ "$(download_count)" = "$downloads" ] || fail "symlink refusal fetched a release archive"
rm -f "$private"
mv "$private.exact-bytes" "$private"

chmod 04755 "$private"
[ "$(stat -c '%a' "$private")" = 4755 ] || fail "setuid payload fixture did not retain 04755"
if bash "$tmp/detect.sh"; then fail "Detect accepted a 04755 payload as managed 0755"; fi
if bash "$tmp/verify.sh"; then fail "Verify accepted a 04755 payload as managed 0755"; fi
if bash "$tmp/fix.sh"; then fail "Fix accepted a special-mode payload"; fi
[ "$(stat -c '%a' "$private")" = 4755 ] || fail "failed-closed Fix mutated the special-mode payload"
[ "$(download_count)" = "$downloads" ] || fail "special-mode refusal fetched a release archive"
chmod 0755 "$private"

for managed_dir in "$meta/usr/bin" "$meta/.toolchains/sqld" "$meta/.toolchains/sqld/bin" \
  "$meta/usr/libexec/envctl/sqld" "$meta/usr/libexec/envctl/sqld/bin" \
  "$meta/usr/libexec/envctl/sqld/bin/current"; do
  [ -d "$managed_dir" ] && [ ! -L "$managed_dir" ] && [ "$(stat -c '%a' "$managed_dir")" = 755 ] \
    || fail "installed sqld runtime directory has unsafe shape: $managed_dir"
done

prepare_failure_hash="$(/usr/bin/sha256sum "$private" "$front" "$managed_probe" "$managed_probe_digest" "$managed_probe_source")"
systemctl_lines_before="$(wc -l <"$SQLD_SYSTEMCTL_LOG")"
export SQLD_TEST_REMOVE_MKTEMP_FAIL=1
if bash "$tmp/remove.sh"; then fail "remove ignored retirement-path preparation failure"; fi
unset SQLD_TEST_REMOVE_MKTEMP_FAIL
[ "$(/usr/bin/sha256sum "$private" "$front" "$managed_probe" "$managed_probe_digest" "$managed_probe_source")" = "$prepare_failure_hash" ] \
  || fail "retirement-path preparation failure mutated runtime bytes"
[ "$(wc -l <"$SQLD_SYSTEMCTL_LOG")" = "$systemctl_lines_before" ] \
  || fail "retirement-path preparation failure reached service mutation"
[ -z "$(find "$meta/usr/bin" "$meta/.toolchains/sqld" "$meta/usr/libexec/envctl/sqld" \
  -maxdepth 1 \( -name '.sqld.remove.*' -o -name '.bin.retired.*' \) -print -quit)" ] \
  || fail "retirement-path preparation failure leaked a placeholder"

query_failure_hash="$(/usr/bin/sha256sum "$private" "$front" "$managed_probe" "$managed_probe_digest" "$managed_probe_source")"
export SQLD_SYSTEMCTL_QUERY_STATE=fail
if bash "$tmp/remove.sh"; then fail "remove ignored a failed sqld service-state query"; fi
unset SQLD_SYSTEMCTL_QUERY_STATE
[ "$(/usr/bin/sha256sum "$private" "$front" "$managed_probe" "$managed_probe_digest" "$managed_probe_source")" = "$query_failure_hash" ] \
  || fail "failed sqld service-state query mutated runtime bytes"

stop_failure_hash="$(/usr/bin/sha256sum "$private" "$front" "$managed_key" "$managed_token" "$managed_probe" "$managed_probe_digest" "$managed_probe_source" "$meta/var/lib/sqld/data-marker")"
restores_before="$(grep -Fc -- '--user enable --now sqld.service' "$SQLD_SYSTEMCTL_LOG" || true)"
export SQLD_STOP_STATE=fail
if bash "$tmp/remove.sh"; then fail "remove ignored a failed sqld stop/disable"; fi
unset SQLD_STOP_STATE
[ "$(/usr/bin/sha256sum "$private" "$front" "$managed_key" "$managed_token" "$managed_probe" "$managed_probe_digest" "$managed_probe_source" "$meta/var/lib/sqld/data-marker")" = "$stop_failure_hash" ] \
  || fail "failed sqld stop mutated binary, auth material, or durable data"
[ "$(grep -Fc -- '--user enable --now sqld.service' "$SQLD_SYSTEMCTL_LOG" || true)" = "$((restores_before + 1))" ] \
  || fail "partially failed sqld stop/disable did not restore prior service state"

# Namespace retirement is transactional with service state. Both a rename failure after the first
# retirement and a directory-fsync failure restore every namespace and the active/enabled unit.
for injection in mv sync; do
  retirement_hash="$(/usr/bin/sha256sum "$private" "$front" "$managed_probe" "$managed_probe_digest" "$managed_probe_source")"
  restores_before="$(grep -Fc -- '--user enable --now sqld.service' "$SQLD_SYSTEMCTL_LOG" || true)"
  if [ "$injection" = mv ]; then
    export SQLD_TEST_REMOVE_MV_FAIL_AT=2
  else
    export SQLD_TEST_REMOVE_SYNC_FAIL_AT=2
  fi
  if bash "$tmp/remove.sh"; then fail "remove ignored an injected $injection retirement failure"; fi
  unset SQLD_TEST_REMOVE_MV_FAIL_AT SQLD_TEST_REMOVE_SYNC_FAIL_AT
  [ "$(/usr/bin/sha256sum "$private" "$front" "$managed_probe" "$managed_probe_digest" "$managed_probe_source")" = "$retirement_hash" ] \
    || fail "injected $injection retirement failure did not restore all runtime namespaces"
  [ "$(grep -Fc -- '--user enable --now sqld.service' "$SQLD_SYSTEMCTL_LOG" || true)" = "$((restores_before + 1))" ] \
    || fail "injected $injection retirement failure did not restore service state"
done

# A frontdoor exchange failure after a fresh helper generation must roll the helper back as part
# of the same runtime transaction. The exact legacy wrapper is a safe upgradeable incumbent.
printf '%s\n' '#!/bin/sh' "exec \"$private\" \"\$@\"" >"$front"
chmod 0755 "$front"
front_failure_hash="$(/usr/bin/sha256sum "$private" "$front" "$managed_probe" "$managed_probe_digest" "$managed_probe_source")"
export SQLD_TEST_MV_FAIL_AT=2
if bash "$tmp/install.sh"; then fail "install ignored an injected frontdoor exchange failure"; fi
unset SQLD_TEST_MV_FAIL_AT
[ "$(/usr/bin/sha256sum "$private" "$front" "$managed_probe" "$managed_probe_digest" "$managed_probe_source")" = "$front_failure_hash" ] \
  || fail "frontdoor exchange failure did not roll back the complete runtime transaction"
bash "$tmp/install.sh"

printf '#!/bin/sh\necho foreign\n' >"$front"
chmod 755 "$front"
if bash "$tmp/fix.sh"; then fail "fix clobbered a foreign frontdoor"; fi
grep -Fq foreign "$front" || fail "foreign frontdoor content changed"
foreign_hash="$(/usr/bin/sha256sum "$private" "$front" "$managed_probe" "$managed_probe_digest" "$managed_probe_source")"
systemctl_lines_before="$(wc -l <"$SQLD_SYSTEMCTL_LOG")"
if bash "$tmp/remove.sh"; then fail "remove accepted a foreign frontdoor"; fi
grep -Fq foreign "$front" || fail "remove deleted a foreign frontdoor"
[ "$(/usr/bin/sha256sum "$private" "$front" "$managed_probe" "$managed_probe_digest" "$managed_probe_source")" = "$foreign_hash" ] \
  || fail "foreign-frontdoor removal refusal mutated managed runtime state"
[ "$(wc -l <"$SQLD_SYSTEMCTL_LOG")" = "$systemctl_lines_before" ] \
  || fail "foreign-frontdoor removal reached service state before identity preflight"
[ -f "$managed_key" ] && [ -f "$managed_token" ] || fail "remove deleted authentication material"
if bash "$tmp/install.sh"; then fail "install clobbered a foreign frontdoor"; fi
grep -Fq foreign "$front" || fail "install changed a foreign frontdoor"
[ -e "$private" ] || fail "refused foreign-frontdoor install deleted the incumbent payload"
[ -f "$meta/var/lib/sqld/data-marker" ] || fail "remove deleted durable data"

rm -f "$front"
bash "$tmp/install.sh"

# Remove authenticates the adjacent helper record but never executes the to-be-removed helper.
# A forged self-consistent triple is therefore safe to retire without handing attacker bytes any
# lifecycle arguments, token path, or execution opportunity.
remove_forged_marker="$tmp/remove-forged-helper-executed"
cat >"$managed_probe" <<SH
#!/usr/bin/env bash
: >"$remove_forged_marker"
exit 99
SH
chmod 0755 "$managed_probe"
/usr/bin/sha256sum "$managed_probe" >"$managed_probe_digest"
chmod 0600 "$managed_probe_digest"
printf '%s\n' "$managed_source_identity" >"$managed_probe_source"
chmod 0600 "$managed_probe_source"
PATH="$lifecycle_shadow_bin:$PATH" bash "$tmp/remove.sh"
[ ! -e "$lifecycle_shadow_marker" ] || fail "sqld Remove executed a caller PATH shadow"
[ ! -e "$remove_forged_marker" ] || fail "sqld Remove executed the to-be-removed helper"
[ ! -e "$front" ] && [ ! -L "$front" ] || fail "managed frontdoor survived remove"
[ ! -e "$private" ] || fail "managed payload survived remove"
[ ! -e "$managed_probe" ] || fail "managed readiness helper survived remove"
[ ! -e "$managed_probe_digest" ] || fail "managed readiness-helper digest survived remove"
[ ! -e "$managed_probe_source" ] || fail "managed readiness-helper source identity survived remove"
[ -f "$meta/var/lib/sqld/data-marker" ] || fail "managed remove deleted durable data"
[ -f "$managed_key" ] && [ -f "$managed_token" ] || fail "managed remove deleted authentication material"
rm -f "$meta/.config/systemd/user/sqld.service"
export SQLD_LOAD_STATE=not-found SQLD_ACTIVE_STATE=inactive
bash "$tmp/remove.sh"
unset SQLD_LOAD_STATE SQLD_ACTIVE_STATE
[ ! -e "$front" ] && [ ! -e "$private" ] && [ ! -e "$managed_probe" ] \
  || fail "second remove recreated or retained sqld runtime state"

meta_aarch="$tmp/meta-aarch"
mkdir -p "$meta_aarch/var/lib/sqld"
chmod 0700 "$meta_aarch/var/lib/sqld"
seed_meta_toolchain "$meta_aarch"
export META_ROOT="$meta_aarch"
export SQLD_TEST_ARCH=aarch64
bash "$tmp/install.sh"
grep -Fq 'libsql-server-v0.24.32/libsql-server-aarch64-unknown-linux-gnu.tar.xz' "$SQLD_CURL_LOG" \
  || fail "aarch64 release URL is not pinned to v0.24.32"
grep -Fq '37f9eee45b388a30192907ecf4565b93df945c079331657073b5b3caf8bb1cd0' "$SQLD_SHA_LOG" \
  || fail "aarch64 release checksum was not verified"
grep -Fq "$fixture_payload_sha256" "$SQLD_SHA_LOG" \
  || fail "installed aarch64 payload digest was not verified"

# With no operator-supplied sources, the component must invoke the hidden pure-Rust generator.
meta_bootstrap="$tmp/meta-bootstrap"
mkdir -p "$meta_bootstrap/var/lib/sqld"
chmod 0700 "$meta_bootstrap/var/lib/sqld"
seed_meta_toolchain "$meta_bootstrap"
export META_ROOT="$meta_bootstrap"
export SQLD_TEST_ARCH=x86_64
export ENVCTL_SOURCE_ROOT="$fixture_source"
unset SQLD_AUTH_JWT_KEY_SOURCE SQLD_CLIENT_JWT_SOURCE
rustup_calls_before="$(wc -l <"$SQLD_RUSTUP_LOG")"
bash "$tmp/install.sh"
bootstrap_key="$meta_bootstrap/.config/sqld/auth-jwt-key.pem"
bootstrap_token="$meta_bootstrap/.config/sqld/client.jwt"
[ -s "$bootstrap_key" ] && [ -s "$bootstrap_token" ] || fail "Rust-native bootstrap did not create both auth files"
[ "$(stat -c '%a' "$bootstrap_key")" = 600 ] && [ "$(stat -c '%a' "$bootstrap_token")" = 600 ] \
  || fail "Rust-native bootstrap outputs are not 0600"
[ "$(wc -l <"$SQLD_RUSTUP_LOG")" = "$((rustup_calls_before + 1))" ] \
  || fail "unattended install did not build the Rust-native helper exactly once"
grep -Eq '^build --quiet --frozen --locked --offline --release --manifest-path /[^ ]+/Cargo\.toml --package envctl-secretctl --bin secretctl$' \
  "$SQLD_RUSTUP_LOG" \
  || fail "sqld helper did not use direct pinned Cargo with the frozen locked offline workspace"
grep -Fq 'internal-sqld-auth-bootstrap' "$SQLD_PROBE_LOG" \
  || fail "sqld bootstrap did not invoke the private Rust-native helper"
if grep -Fq 'generated.client.jwt-fixture' "$SQLD_RUSTUP_LOG" "$SQLD_PROBE_LOG"; then
  fail "generated client JWT leaked into the bootstrap argv/log"
fi
bash "$tmp/fix.sh"
[ "$(wc -l <"$SQLD_RUSTUP_LOG")" = "$((rustup_calls_before + 2))" ] \
  || fail "idempotent fix did not rebuild the helper exactly once"
[ "$(grep -c '^internal-sqld-auth-bootstrap ' "$SQLD_PROBE_LOG" || true)" = 1 ] \
  || fail "idempotent fix regenerated an existing sqld auth pair"

# A partial managed pair is ambiguous and must be preserved rather than filled or overwritten.
meta_partial="$tmp/meta-partial"
mkdir -p "$meta_partial/.config/sqld" "$meta_partial/var/lib/sqld"
chmod 0700 "$meta_partial/.config/sqld" "$meta_partial/var/lib/sqld"
seed_meta_toolchain "$meta_partial"
printf '%s\n' 'operator-owned-public-key' >"$meta_partial/.config/sqld/auth-jwt-key.pem"
chmod 0600 "$meta_partial/.config/sqld/auth-jwt-key.pem"
export META_ROOT="$meta_partial"
partial_calls_before="$(wc -l <"$SQLD_RUSTUP_LOG")"
partial_bootstraps_before="$(grep -c '^internal-sqld-auth-bootstrap ' "$SQLD_PROBE_LOG" || true)"
if bash "$tmp/install.sh"; then fail "install filled a partial sqld auth pair"; fi
[ "$(cat "$meta_partial/.config/sqld/auth-jwt-key.pem")" = 'operator-owned-public-key' ] \
  || fail "partial-state refusal changed the existing sqld public key"
[ ! -e "$meta_partial/.config/sqld/client.jwt" ] || fail "partial-state refusal created a client JWT"
[ "$(wc -l <"$SQLD_RUSTUP_LOG")" = "$partial_calls_before" ] \
  || fail "partial-state preflight started a Rust build"
[ "$(grep -c '^internal-sqld-auth-bootstrap ' "$SQLD_PROBE_LOG" || true)" = "$partial_bootstraps_before" ] \
  || fail "partial-state refusal invoked the credential generator"

# The credential directory itself is a trust boundary: never follow a substituted symlink.
meta_unsafe_dir="$tmp/meta-unsafe-dir"
outside_auth="$tmp/outside-auth"
mkdir -p "$meta_unsafe_dir/.config" "$meta_unsafe_dir/var/lib/sqld" "$outside_auth"
chmod 0700 "$meta_unsafe_dir/var/lib/sqld"
seed_meta_toolchain "$meta_unsafe_dir"
ln -s "$outside_auth" "$meta_unsafe_dir/.config/sqld"
export META_ROOT="$meta_unsafe_dir"
unsafe_calls_before="$(wc -l <"$SQLD_RUSTUP_LOG")"
if bash "$tmp/install.sh"; then fail "install accepted a symlinked sqld auth directory"; fi
[ -z "$(find "$outside_auth" -mindepth 1 -print -quit)" ] || fail "unsafe auth-dir refusal wrote through the symlink"
[ "$(wc -l <"$SQLD_RUSTUP_LOG")" = "$unsafe_calls_before" ] \
  || fail "unsafe auth-dir refusal invoked the credential generator"

# Optional real-binary probe used by the release-pin verification lane. It exercises the actual
# pinned sqld parser/verifier with material emitted by the built secretctl command; the default
# hermetic test remains network- and port-free.
if [ -n "${SQLD_REAL_BIN:-}" ]; then
  [ -x "$SQLD_REAL_BIN" ] || fail "SQLD_REAL_BIN is not executable"
  [ -x "${SQLD_REAL_SECRETCTL_BIN:-}" ] || fail "SQLD_REAL_SECRETCTL_BIN is not executable"
  (
    set -euo pipefail
    real_dir="$tmp/real-auth-probe"
    real_port="${SQLD_REAL_PORT:-18082}"
    mkdir -p "$real_dir/db"
    "$SQLD_REAL_SECRETCTL_BIN" internal-sqld-auth-bootstrap \
      --public-key "$real_dir/auth-jwt-key.pem" --client-token "$real_dir/client.jwt"
    "$SQLD_REAL_BIN" --http-listen-addr "127.0.0.1:$real_port" \
      --auth-jwt-key-file "$real_dir/auth-jwt-key.pem" -d "$real_dir/db" \
      >"$real_dir/sqld.log" 2>&1 &
    sqld_pid=$!
    trap 'kill "$sqld_pid" 2>/dev/null || true; wait "$sqld_pid" 2>/dev/null || true' EXIT
    ready=0
    for _ in $(seq 1 100); do
      if /usr/bin/curl --fail --silent --max-time 1 "http://127.0.0.1:$real_port/health" >/dev/null 2>&1; then
        ready=1
        break
      fi
      sleep 0.05
    done
    [ "$ready" = 1 ] || { cat "$real_dir/sqld.log" >&2; fail "real pinned sqld did not become ready"; }
    "$SQLD_REAL_SECRETCTL_BIN" internal-sqld-self-digest \
      --output "$real_dir/secretctl.sha256"
    "$SQLD_REAL_SECRETCTL_BIN" internal-sqld-readiness-probe \
      --pid "$sqld_pid" --expected-executable "$SQLD_REAL_BIN" --port "$real_port" \
      --client-token "$real_dir/client.jwt" --helper-digest "$real_dir/secretctl.sha256" \
      --timeout-seconds 5 \
      || fail "real pinned sqld failed the Rust-native MainPID/auth readiness barrier"
  )
fi

if grep -Eq '(%h/Desktop/meta|/home/[^/]+/(Desktop/)?meta)' "$manifest"; then
  fail "sqld component contains a workstation-specific meta path"
fi
if grep -Fq 'SQLD_VERSION' "$manifest"; then
  fail "sqld component still permits an unpinned version override"
fi
# These are intentionally literal shell snippets from the TOML hook.
# shellcheck disable=SC2016
grep -Fq 'mktemp "$M/usr/bin/.sqld.XXXXXX"' "$manifest" \
  || fail "sqld frontdoor is not staged in its destination directory"
# shellcheck disable=SC2016
grep -Fq 'sqld_mv -T --exchange --no-copy -- "$staged_front" "$front"' "$manifest" \
  || fail "sqld frontdoor replacement is not an atomic same-filesystem exchange"
grep -Fq 'pub const RUNTIME_FILESYSTEM_UUID: &str = "runtime"' "$root/crates/engine/src/guard.rs" \
  || fail "engine does not own the runtime filesystem identity sentinel"
grep -Fq 'Environment="SECRETD_LIBSQL_AUTH_TOKEN_FILE=${META_ROOT}/.config/sqld/client.jwt"' \
  "$root/manifest/env-ctl.toml" \
  || fail "secretd is not wired to the managed 0600 sqld client JWT"

# The production service must be strictly coupled to the owned sqld and remain `activating` until
# its authenticated libSQL builder has connected and provisioned the schema. This is deliberately
# source/static and hermetic: it tests the systemd contract without depending on a user manager.
env_unit="$root/manifest/env-ctl.toml"
for contract in \
  'Requires=sqld.service' \
  'BindsTo=sqld.service' \
  'After=sqld.service' \
  'Type=notify' \
  'Environment="SECRETD_STORE_BACKEND=libsql"' \
  'Environment="SECRETD_LIBSQL_URL=http://127.0.0.1:8080"' \
  'ConditionPathExists="${META_ROOT}/.config/sqld/auth-jwt-key.pem"' \
  'ConditionPathExists="${META_ROOT}/.config/sqld/client.jwt"'
do
  grep -Fqx "$contract" "$env_unit" \
    || fail "secretd/sqld readiness contract is missing '$contract'"
done
if grep -Fqx 'Wants=sqld.service' "$env_unit"; then
  fail "secretd/sqld readiness contract regressed to Wants="
fi
# Pin the gate root explicitly so an ambient nested-gate override cannot redirect this positive
# control to a partially populated fixture tree.
ENVCTL_GATE_ROOT="$root" bash "$root/ci/gates/enable.sh" >/dev/null \
  || fail "secretd/sqld systemd readiness gate failed"

# Fail-closed mutation: `After=sqld.service` without sqld's non-ignored ExecStartPost is only process
# ordering, not readiness. The CI gate must reject that exact regression hermetically.
gate_root="$tmp/readiness-gate"
mkdir -p "$gate_root/manifest" "$gate_root/crates/secretd/src" \
  "$gate_root/crates/secrets-store-libsql/src" "$gate_root/crates/secretctl/src" \
  "$gate_root/manifest/components.d" "$gate_root/assets/scripts" "$gate_root/scripts/tests"
cp "$root/manifest/env-ctl.toml" "$gate_root/manifest/env-ctl.toml"
cp "$root/manifest/sqld.toml" "$gate_root/manifest/sqld.toml"
cp "$root/crates/secretd/src/main.rs" "$gate_root/crates/secretd/src/main.rs"
cp "$root/crates/secrets-store-libsql/src/store.rs" "$gate_root/crates/secrets-store-libsql/src/store.rs"
cp "$root/crates/secretctl/src/cli.rs" "$gate_root/crates/secretctl/src/cli.rs"
cp "$root/crates/secretctl/src/sqld_auth.rs" "$gate_root/crates/secretctl/src/sqld_auth.rs"
cp "$root/manifest/components.d/epic-h-toolchains.toml" "$gate_root/manifest/components.d/epic-h-toolchains.toml"
cp "$root/assets/scripts/envctl-sqld-hermetic-cargo.sh" "$gate_root/assets/scripts/envctl-sqld-hermetic-cargo.sh"
cp "$root/assets/scripts/envctl-llvm-clang-lifecycle.sh" "$gate_root/assets/scripts/envctl-llvm-clang-lifecycle.sh"
cp "$root/scripts/tests/test-llvm-clang-component.sh" "$gate_root/scripts/tests/test-llvm-clang-component.sh"
chmod 755 "$gate_root/assets/scripts/envctl-sqld-hermetic-cargo.sh" \
  "$gate_root/assets/scripts/envctl-llvm-clang-lifecycle.sh" \
  "$gate_root/scripts/tests/test-llvm-clang-component.sh"
sed -i '/^ExecStartPost=.*internal-sqld-readiness-probe/d' "$gate_root/manifest/sqld.toml"
if ENVCTL_GATE_ROOT="$gate_root" bash "$root/ci/gates/enable.sh" >/dev/null 2>&1; then
  fail "readiness gate accepted After=sqld.service without its ExecStartPost auth barrier"
fi

cp "$root/manifest/sqld.toml" "$gate_root/manifest/sqld.toml"
sed -i '/internal-sqld-verify-current-helper/d' "$gate_root/manifest/sqld.toml"
if ENVCTL_GATE_ROOT="$gate_root" bash "$root/ci/gates/enable.sh" >/dev/null 2>&1; then
  fail "readiness gate accepted sqld lifecycle hooks without fresh-helper byte equality"
fi
[ ! -e "$SQLD_COMPILER_SHADOW_MARKER" ] \
  || fail "sqld helper build executed a compiler/linker shadow from the caller PATH"

echo "PASS: sqld v0.24.32 is digest-pinned, authenticated, health-gated, portable-purge-guarded, and data-safe"
