#!/usr/bin/env bash
# Markdown literals intentionally contain backticks.
# shellcheck disable=SC2016
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

mkdir -p "$tmp/envctl/scripts" "$tmp/yazelix/docs/generated"
cp "$repo_root/scripts/export-codedb-upload-lists.sh" "$tmp/envctl/scripts/"

cat >"$tmp/yazelix/docs/generated/yazelix_file_target_inventory.json" <<'JSON'
[
  {
    "absolute_path": "/stable/content.toml",
    "import_mode": "content_blob",
    "source_of_truth_class": "fixture"
  },
  {
    "absolute_path": "/stable/metadata.bin",
    "import_mode": "metadata_only",
    "source_of_truth_class": "fixture"
  }
]
JSON

bash "$tmp/envctl/scripts/export-codedb-upload-lists.sh" >/dev/null

generated="$tmp/envctl/docs/generated"
diff -u <(printf '%s\n' /stable/content.toml /stable/metadata.bin) \
  "$generated/codedb-import-targets.txt"
diff -u <(printf '%s\n' /stable/content.toml) \
  "$generated/codedb-content-blob-targets.txt"
diff -u <(printf '%s\n' /stable/metadata.bin) \
  "$generated/codedb-metadata-only-targets.txt"
summary="$generated/codedb-upload-inventory.md"
[ -f "$summary" ] || {
  echo "exporter did not render its inventory summary" >&2
  exit 1
}
grep -Fq -- '- total rows: `2`' "$summary"
grep -Fq -- '- content-blob uploads: `1`' "$summary"
grep -Fq -- '- metadata-only targets: `1`' "$summary"
grep -Fq 'Generated by `scripts/export-codedb-upload-lists.sh`' "$summary"

if rg -n '/home/flexnetos/(FlexNetOS|lifeos)' "$tmp/envctl"; then
  echo "exporter retained a retired repository default" >&2
  exit 1
fi

echo "CodeDB upload-list exporter contract: PASS"
