#!/usr/bin/env nu

use ./meta-paths.nu *

# Build durable envctl table registry and generated-output overwrite guards.
# This is a read-only scanner over declared envctl tables and generated targets;
# it does not render or apply runtime config.

def source-role-for-table [table_name: string] {
    if ($table_name | str ends-with "_parser") {
        "evidence"
    } else if $table_name in [
        env_files
        env_files_nushell_inventory
        env_vars_parsed
        nushell_env_config_parsed
    ] {
        "staging"
    } else if $table_name in [
        bootstrap_env_vars
        bootstrap_generated_files
        codex_state_locations
        conflicts
        env_precedence
        secrets
        tool_versions
        rtk_integration_config
        yazelix_settings_overlay
    ] {
        "canonical"
    } else {
        "canonical_seed"
    }
}

def durable-role-for-source [source_role: string] {
    if $source_role == "evidence" {
        "evidence_not_source_of_truth"
    } else if $source_role == "staging" {
        "accepted_input_until_canonical_projection"
    } else if $source_role == "canonical_seed" {
        "seed_source_of_truth"
    } else {
        "source_of_truth"
    }
}

def owner-task-for-table [table_name: string] {
    if $table_name in [bootstrap_env_vars bootstrap_generated_files] {
        "T006"
    } else if $table_name in [codex_state_locations yazelix_tool_locations yazelix_settings_overlay rtk_integration_config rtk_tool_install kache_tool_install wild_tool_install nushell_runtime_evidence] {
        "T011-T025"
    } else if $table_name in [envctl_failure_reproduction envctl_manifest_repair envctl_schema_design] {
        "T027"
    } else if $table_name == "env_files" {
        "T028"
    } else if $table_name == "env_files_nushell_inventory" {
        "T029"
    } else if $table_name in [env_vars_parsed env_vars_parser] {
        "T030"
    } else if $table_name in [nushell_env_config_parsed nushell_env_parser] {
        "T031"
    } else if $table_name in [tool_versions tool_versions_parser] {
        "T032"
    } else if $table_name in [secrets secrets_parser] {
        "T033"
    } else if $table_name in [env_precedence conflicts env_precedence_parser] {
        "T034"
    } else if $table_name in [envctl_tables generated_file_guards table_persistence_parser] {
        "T035"
    } else {
        "unknown"
    }
}

def table-row [path: string] {
    let parsed = ($path | path parse)
    let table_name = ($parsed | get stem)
    let source_role = (source-role-for-table $table_name)
    let rows = (open $path)
    let columns = ($rows | columns)
    {
        table_id: $"table_($table_name)"
        table_name: $table_name
        path: $path
        table_kind: "envctl_csv"
        durable_role: (durable-role-for-source $source_role)
        source_role: $source_role
        row_count: (($rows | length) | into string)
        column_count: (($columns | length) | into string)
        column_names: ($columns | str join ";")
        source_checksum: (open --raw $path | hash sha256)
        generated_by_task: (owner-task-for-table $table_name)
        input_policy: "current_repo_files_remain_accepted_inputs_until_table_first_behavior_lands"
        write_policy: "manual_reviewable_row_edits_only"
        apply_policy: "read_only_catalog_diff_render_first_lock_apply_after_review"
        overwrite_guard: "refuse_silent_overwrite_of_hand_authored_sources"
        manual_review_required: "true"
        validation_status: "ok"
        notes: "Durable envctl table registry row generated by T035 persistence scanner."
    }
}

def declared-output-table-row [
    table_name: string
    path: string
    notes: string
] {
    let source_role = "canonical"
    {
        table_id: $"table_($table_name)"
        table_name: $table_name
        path: $path
        table_kind: "envctl_csv"
        durable_role: (durable-role-for-source $source_role)
        source_role: $source_role
        row_count: "generated_by_T035"
        column_count: "generated_by_T035"
        column_names: "generated_by_T035"
        source_checksum: "self_referential_deferred"
        generated_by_task: "T035"
        input_policy: "current_repo_files_remain_accepted_inputs_until_table_first_behavior_lands"
        write_policy: "manual_reviewable_row_edits_only"
        apply_policy: "read_only_catalog_diff_render_first_lock_apply_after_review"
        overwrite_guard: "refuse_silent_overwrite_of_hand_authored_sources"
        manual_review_required: "true"
        validation_status: "ok"
        notes: $notes
    }
}

def table-registry [] {
    let tables_root = (tables-root "")
    let generated_this_task = [envctl_tables generated_file_guards table_persistence_parser]
    let scanned = (
        ls $tables_root
        | where type == file
        | where name =~ '\.csv$'
        | where {|row| (($row.name | path parse | get stem) not-in $generated_this_task)}
        | sort-by name
        | each {|row| table-row ($row.name | into string)}
    )
    let declared = [
        (declared-output-table-row "envctl_tables" $"($tables_root)/envctl_tables.csv" "T035 durable table registry output; checksum is self-referential and deferred to release manifest.")
        (declared-output-table-row "generated_file_guards" $"($tables_root)/generated_file_guards.csv" "T035 generated-output guard table; checksum is self-referential and deferred to release manifest.")
        (declared-output-table-row "table_persistence_parser" $"($tables_root)/table_persistence_parser.csv" "T035 evidence table; checksum is self-referential and deferred to release manifest.")
    ]
    $scanned ++ $declared
}

def generated-target-row [
    artifact_id: string
    target_path: string
    role: string
    source_table: string
    owner_task: string
    declared_status: string
    notes: string
    env_files: list
] {
    let overlaps = ($env_files | where {|row| $row.path == $target_path})
    let hand_authored = (($overlaps | where source_role == "original" | where mutability != "generated" | length) > 0)
    let managed_table_output = ($role == "generated_table")
    let exists = (if $managed_table_output { false } else { $target_path | path exists })
    let overlap_refs = if ($overlaps | length) == 0 {
        ""
    } else {
        $overlaps | get file_id | str join ";"
    }
    let status = if $hand_authored {
        "blocked_hand_authored_overlap"
    } else if $exists {
        "existing_target_requires_diff"
    } else {
        "ok_declared_not_generated"
    }
    {
        guard_id: $"guard_($artifact_id)"
        artifact_id: $artifact_id
        target_path: $target_path
        role: $role
        source_table: $source_table
        owner_task: $owner_task
        declared_status: $declared_status
        target_exists: (if $managed_table_output { "managed_table_output" } else { $exists | into string })
        env_files_overlap: $overlap_refs
        hand_authored_overlap: ($hand_authored | into string)
        silent_overwrite_guard: (if $hand_authored { "fail" } else { "pass" })
        overwrite_allowed: "manual_review_and_diff_only"
        requires_diff: "true"
        requires_manual_gate: "true"
        validation_status: (if $hand_authored { "error" } else { "ok" })
        source_reference: "bootstrap_generated_files.csv;env_files.csv;T035"
        notes: $notes
    }
}

def generated-file-guards [] {
    let tables_root = (tables-root "")
    let env_files = (open $"($tables_root)/env_files.csv")
    let runtime_targets = (
        open $"($tables_root)/bootstrap_generated_files.csv"
        | each {|row|
            generated-target-row $row.artifact_id $row.path $row.role $row.source_table $row.owner_task $row.status $row.notes $env_files
        }
    )
    let table_targets = [
        (generated-target-row "envctl_tables" $"($tables_root)/envctl_tables.csv" "generated_table" "envctl_tables.csv" "T035" "declared_generated_table" "Durable table registry output; generated only from envctl tables and never to a hand-authored source path." $env_files)
        (generated-target-row "generated_file_guards" $"($tables_root)/generated_file_guards.csv" "generated_table" "envctl_tables.csv" "T035" "declared_generated_table" "Generated overwrite guard table; generated only from envctl tables and never to a hand-authored source path." $env_files)
        (generated-target-row "table_persistence_parser" $"($tables_root)/table_persistence_parser.csv" "generated_table" "envctl_tables.csv" "T035" "declared_generated_table" "T035 evidence table; generated only from envctl tables and never to a hand-authored source path." $env_files)
    ]
    $runtime_targets ++ $table_targets
}

def main [
    table: string = "registry"
    --json
] {
    let rows = if $table == "registry" {
        table-registry
    } else if $table == "guards" {
        generated-file-guards
    } else {
        error make {msg: $"unsupported table '($table)'; expected registry or guards"}
    }

    if $json {
        $rows | to json
    } else {
        $rows
    }
}
