#!/usr/bin/env bash
# Markdown literals intentionally contain backticks.
# shellcheck disable=SC2016
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
sibling_root="$(dirname "$repo_root")"
manifest_default="$sibling_root/yazelix/docs/generated/yazelix_file_target_inventory.json"
manifest_path="${1:-${YAZELIX_FILE_INVENTORY:-$manifest_default}}"
output_dir="${CODEDB_UPLOAD_OUTPUT_DIR:-$repo_root/docs/generated}"

if [[ ! -f "$manifest_path" ]]; then
  echo "manifest not found: $manifest_path" >&2
  exit 1
fi

if ! jq -e '
  type == "array" and all(.[];
    (.absolute_path | type == "string" and startswith("/")) and
    (.import_mode == "content_blob" or .import_mode == "metadata_only") and
    (.source_of_truth_class | type == "string" and length > 0)
  )
' "$manifest_path" >/dev/null; then
  echo "manifest is not a valid Yazelix file-target inventory: $manifest_path" >&2
  exit 1
fi

mkdir -p "$output_dir"

all_targets="$output_dir/codedb-import-targets.txt"
blob_targets="$output_dir/codedb-content-blob-targets.txt"
metadata_targets="$output_dir/codedb-metadata-only-targets.txt"
summary="$output_dir/codedb-upload-inventory.md"

jq -r '[.[] | .absolute_path] | sort[]' "$manifest_path" > "$all_targets"
jq -r '[.[] | select(.import_mode=="content_blob") | .absolute_path] | sort[]' "$manifest_path" > "$blob_targets"
jq -r '[.[] | select(.import_mode=="metadata_only") | .absolute_path] | sort[]' "$manifest_path" > "$metadata_targets"

snapshot_date="${CODEDB_INVENTORY_DATE:-$(date -u +%F)}"
manifest_label="${CODEDB_UPLOAD_MANIFEST_LABEL:-$manifest_path}"
total_rows="$(jq 'length' "$manifest_path")"
content_rows="$(jq '[.[] | select(.import_mode=="content_blob")] | length' "$manifest_path")"
metadata_rows="$(jq '[.[] | select(.import_mode=="metadata_only")] | length' "$manifest_path")"

{
  printf '%s\n\n' '# CodeDB Upload Inventory'
  printf 'Generated by `scripts/export-codedb-upload-lists.sh` on `%s`.\n\n' "$snapshot_date"
  printf 'Source manifest: `%s`\n\n' "$manifest_label"
  printf '%s\n\n' \
    'This is an audit projection, not authority to activate every observed runtime, plugin, MCP, cache, or generated output. Yazelix and envctl ownership policy remains authoritative.'
  printf '%s\n\n' '## Row counts'
  printf -- '- total rows: `%s`\n' "$total_rows"
  printf -- '- content-blob uploads: `%s`\n' "$content_rows"
  printf -- '- metadata-only targets: `%s`\n\n' "$metadata_rows"
  printf '%s\n\n' '## Source-of-truth classes'
  printf '%s\n' '| class | total | content blob | metadata only |'
  printf '%s\n' '| --- | ---: | ---: | ---: |'
  jq -r '
    sort_by(.source_of_truth_class)
    | group_by(.source_of_truth_class)[]
    | "| `\(.[0].source_of_truth_class)` | `\(length)` | `\(map(select(.import_mode == "content_blob")) | length)` | `\(map(select(.import_mode == "metadata_only")) | length)` |"
  ' "$manifest_path"
  printf '\n%s\n\n' '## Exact projections'
  printf '%s\n' \
    '- `docs/generated/codedb-import-targets.txt` — every target row' \
    '- `docs/generated/codedb-content-blob-targets.txt` — rows whose bytes are eligible for bounded import' \
    '- `docs/generated/codedb-metadata-only-targets.txt` — rows retained without reading file bytes'
  printf '\n%s\n\n' 'Regenerate all four artifacts together:'
  printf '%s\n' '```bash' \
    'bash scripts/export-codedb-upload-lists.sh /home/flexnetos/meta/src/yazelix/docs/generated/yazelix_file_target_inventory.json' \
    '```'
} > "$summary"

echo "wrote:"
echo "  $all_targets"
echo "  $blob_targets"
echo "  $metadata_targets"
echo "  $summary"
