#!/usr/bin/env bash
# Render durable Markdown/text receipts from an envctl catalog-render directory.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
render_dir="${1:?usage: export-catalog-proof-reports.sh RENDER_DIR [OUTPUT_DIR]}"
output_dir="${2:-$repo_root/docs/generated}"
scan="$render_dir/catalog/scan.json"
tables="$render_dir/catalog/tables"

for required in \
  "$scan" \
  "$tables/codedb_file_imports.json" \
  "$tables/config_files.json" \
  "$tables/env_vars.json" \
  "$tables/paths.json" \
  "$tables/settings.json"; do
  [ -f "$required" ] || { printf 'missing catalog projection: %s\n' "$required" >&2; exit 1; }
done

mkdir -p "$output_dir"
snapshot_hash="$(sha256sum "$scan" | cut -d' ' -f1)"
source_remote="$(git -C "$repo_root" remote get-url origin)"
catalog_repo="${CATALOG_PROOF_REPOSITORY:-$source_remote}"
manifest_dir="manifest/"
generated_at="${CATALOG_PROOF_DATE:-$(date -u +%F)}"

all_targets="$output_dir/codedb-import-targets.txt"
blob_targets="$output_dir/codedb-content-blob-targets.txt"
metadata_targets="$output_dir/codedb-metadata-only-targets.txt"
jq -r 'sort_by(.absolute_path)[] | .absolute_path' \
  "$tables/codedb_file_imports.json" >"$all_targets"
jq -r 'map(select(.import_mode == "content_blob")) | sort_by(.absolute_path)[] | .absolute_path' \
  "$tables/codedb_file_imports.json" >"$blob_targets"
jq -r 'map(select(.import_mode == "metadata_only")) | sort_by(.absolute_path)[] | .absolute_path' \
  "$tables/codedb_file_imports.json" >"$metadata_targets"

total_imports="$(jq 'length' "$tables/codedb_file_imports.json")"
content_imports="$(jq '[.[] | select(.import_mode == "content_blob")] | length' "$tables/codedb_file_imports.json")"
metadata_imports="$(jq '[.[] | select(.import_mode == "metadata_only")] | length' "$tables/codedb_file_imports.json")"
{
  printf '# CodeDB Upload Inventory\n\n'
  printf 'Generated by `scripts/export-catalog-proof-reports.sh` on `%s`.\n\n' "$generated_at"
  printf -- '- catalog snapshot SHA-256: `%s`\n' "$snapshot_hash"
  printf -- '- source repository: `%s`\n' "$catalog_repo"
  printf -- '- manifest directory: `%s`\n\n' "$manifest_dir"
  printf 'The current canonical Yazelix source no longer publishes the retired host-file inventory. '
  printf 'These rows therefore come only from the current envctl catalog render; no prior checkout is used as authority.\n\n'
  printf '## Row counts\n\n'
  printf -- '- total rows: `%s`\n' "$total_imports"
  printf -- '- content-blob uploads: `%s`\n' "$content_imports"
  printf -- '- metadata-only targets: `%s`\n\n' "$metadata_imports"
  printf '## Exact projections\n\n'
  printf '%s\n' \
    '- `docs/generated/codedb-import-targets.txt`' \
    '- `docs/generated/codedb-content-blob-targets.txt`' \
    '- `docs/generated/codedb-metadata-only-targets.txt`'
} >"$output_dir/codedb-upload-inventory.md"

config_count="$(jq 'length' "$tables/config_files.json")"
env_count="$(jq 'length' "$tables/env_vars.json")"
{
  printf '# Current envctl Database-Bound File Inventory\n\n'
  printf 'Generated from `envctl catalog render`; manual edits are not authoritative.\n\n'
  printf -- '- snapshot SHA-256: `%s`\n' "$snapshot_hash"
  printf -- '- repository: `%s`\n' "$catalog_repo"
  printf -- '- manifest directory: `%s`\n' "$manifest_dir"
  printf -- '- CodeDB file imports: `%s`\n' "$total_imports"
  printf -- '- catalog config files: `%s`\n' "$config_count"
  printf -- '- environment-variable rows: `%s`\n\n' "$env_count"
  printf '## CodeDB file imports\n\n```text\n'
  jq -r 'sort_by(.absolute_path)[] | .absolute_path' "$tables/codedb_file_imports.json"
  printf '```\n\n## Catalog config files\n\n'
  jq -r 'sort_by(.path)[] | "- `\(.path)` — `\(.file_kind)` / `\(.read_status)` / `\(.parse_status)`"' \
    "$tables/config_files.json"
  printf '\n## Environment-variable names\n\n'
  jq -r 'sort_by(.var_name, .producer, .source)[] | "- `\(.var_name)` — `\(.producer)` (`\(.source)`)"' \
    "$tables/env_vars.json"
} >"$output_dir/current-database-file-inventory.md"

{
  printf '# envctl Environment Variable Inventory\n\n'
  printf 'Generated from catalog snapshot `%s`. Sensitive values are always rendered as `redacted`.\n\n' "$snapshot_hash"
  printf -- '- total rows: `%s`\n' "$env_count"
  printf -- '- repository: `%s`\n' "$catalog_repo"
  printf -- '- manifest directory: `%s`\n\n' "$manifest_dir"
  printf '| var | producer | scope | source | sensitive | current value |\n'
  printf '| --- | --- | --- | --- | --- | --- |\n'
  jq -r '
    sort_by(.var_name, .producer, .source)[]
    | [
        (.var_name | @json),
        (.producer | @json),
        (.scope | @json),
        (.source | @json),
        (if .sensitive then "yes" else "no" end),
        (if .sensitive then "redacted" else (.effective_value // .value // .default_value // "unset" | @json) end)
      ]
    | "| `\(.[0])` | `\(.[1])` | `\(.[2])` | `\(.[3])` | `\(.[4])` | `\(.[5])` |"
  ' "$tables/env_vars.json"
} >"$output_dir/env-var-inventory.md"

signal_regex='rust|cargo|nix|bun|profile|toolchain|kache|wild|clang|gcc|uv|podman'
env_signal_count="$(jq --arg re "$signal_regex" '[.[] | select(([.var_name, .producer, .source] | map((. // "") | tostring) | join(" ")) | test($re; "i"))] | length' "$tables/env_vars.json")"
path_signal_count="$(jq --arg re "$signal_regex" '[.[] | select(([.path_id, .path, .path_kind, .source] | map((. // "") | tostring) | join(" ")) | test($re; "i"))] | length' "$tables/paths.json")"
setting_signal_count="$(jq --arg re "$signal_regex" '[.[] | select(([.setting_key, .source_file, .source_kind, .value] | map((. // "") | tostring) | join(" ")) | test($re; "i"))] | length' "$tables/settings.json")"
{
  printf '# envctl Toolchain Signal Inventory\n\n'
  printf 'Generated from catalog snapshot `%s`.\n\n' "$snapshot_hash"
  printf -- '- environment signals: `%s`\n' "$env_signal_count"
  printf -- '- path signals: `%s`\n' "$path_signal_count"
  printf -- '- setting signals: `%s`\n\n' "$setting_signal_count"
  printf '| kind | key | source | detail |\n'
  printf '| --- | --- | --- | --- |\n'
  jq -r --arg re "$signal_regex" '
    sort_by(.var_name, .producer, .source)[]
    | select(([.var_name, .producer, .source] | map((. // "") | tostring) | join(" ")) | test($re; "i"))
    | "| `env_var` | `\(.var_name | @json)` | `\(.source | @json)` | `producer=\(.producer) scope=\(.scope)` |"
  ' "$tables/env_vars.json"
  jq -r --arg re "$signal_regex" '
    sort_by(.path_id, .path)[]
    | select(([.path_id, .path, .path_kind, .source] | map((. // "") | tostring) | join(" ")) | test($re; "i"))
    | "| `path` | `\(.path_id | @json)` | `\(.source | @json)` | `\(.path | @json)` |"
  ' "$tables/paths.json"
  jq -r --arg re "$signal_regex" '
    sort_by(.setting_key, .source_file)[]
    | select(([.setting_key, .source_file, .source_kind, .value] | map((. // "") | tostring) | join(" ")) | test($re; "i"))
    | "| `setting` | `\(.setting_key | @json)` | `\(.source_file | @json)` | `\(.source_kind)` |"
  ' "$tables/settings.json"
} >"$output_dir/toolchain-signal-inventory.md"

{
  printf '# envctl Catalog Table Inventory\n\n'
  printf 'Generated from catalog snapshot `%s`.\n\n' "$snapshot_hash"
  printf '| table | rows | columns |\n'
  printf '| --- | ---: | --- |\n'
  for table in components nix_components component_hooks paths settings env_vars agent_assets registries config_files codedb_file_imports migration_evidence observed_facts; do
    file="$tables/$table.json"
    rows="$(jq 'length' "$file")"
    columns="$(jq -r 'if length == 0 then "" else (.[0] | keys | join(", ")) end' "$file")"
    printf '| `%s` | `%s` | `%s` |\n' "$table" "$rows" "$columns"
  done
} >"$output_dir/catalog-table-inventory.md"

printf 'catalog proof reports: wrote current projections from %s\n' "$snapshot_hash"
