#!/usr/bin/env nu

use ./meta-paths.nu *

# Generate disposable bootstrap.nu and bootstrap.sh from bootstrap_env_vars.csv.
# Secret refs are intentionally skipped; generated outputs contain public paths
# and local-state locations only.

def sh-quote [value: string] {
    let sq = (char single_quote)
    let dq = (char double_quote)
    let escaped = ($value | str replace -a $sq $"($sq)($dq)($sq)($dq)($sq)")
    $"($sq)($escaped)($sq)"
}

def source-rows [tables_root: string] {
    open ($tables_root | path join "bootstrap_env_vars.csv")
    | where generated_target =~ "bootstrap"
    | where value_kind != "secret_ref"
    | where sensitivity != "secret_ref"
    | sort-by precedence name
}

def source-checksum [tables_root: string] {
    open --raw ($tables_root | path join "bootstrap_env_vars.csv") | hash sha256
}

def header-lines [
    target: string
    checksum: string
    timestamp: string
] {
    [
        "# generated by envctl"
        "# generator: scripts/generate-bootstrap.nu"
        "# source table: bootstrap_env_vars.csv"
        $"# source table checksum: ($checksum)"
        $"# generation timestamp: ($timestamp)"
        "# do not edit directly; update envctl table instead"
        $"# target: ($target)"
    ]
}

def render-nu [
    rows: list
    checksum: string
    timestamp: string
] {
    let prefix = '$env.'
    let assignments = (
        $rows
        | each {|row| $"($prefix)($row.name) = ($row.value | to json)"}
    )
    (header-lines "bootstrap.nu" $checksum $timestamp) ++ [""] ++ $assignments ++ [""]
    | str join "\n"
}

def render-sh [
    rows: list
    checksum: string
    timestamp: string
] {
    let assignments = (
        $rows
        | each {|row| $"export ($row.name)=((sh-quote $row.value))"}
    )
    (header-lines "bootstrap.sh" $checksum $timestamp) ++ [""] ++ ["# shellcheck shell=sh"] ++ $assignments ++ [""]
    | str join "\n"
}

def manifest-row [
    artifact_id: string
    path: string
    format: string
    source_checksum: string
    timestamp: string
] {
    {
        artifact_id: $artifact_id
        path: $path
        format: $format
        generator: "scripts/generate-bootstrap.nu"
        source_table: "bootstrap_env_vars.csv"
        source_table_checksum: $source_checksum
        generation_timestamp: $timestamp
        output_checksum: (open --raw $path | hash sha256)
        header_status: "present"
        manual_edits_allowed: "false"
        diff_required_before_apply: "true"
        secret_policy: "secret_refs_excluded"
        validation_status: "generated"
        notes: "Disposable T036 generated output; live target apply remains gated by generated_file_guards.csv."
    }
}

def main [
    --tables-root: string = ""
    --out-dir: string = ""
    --manifest-out: string = ""
    --timestamp: string = "1970-01-01T00:00:00Z"
    --json
] {
    let root = (meta-root "")
    let tables_root = (if ($tables_root | is-empty) { (tables-root "") } else { $tables_root })
    let out_dir = (if ($out_dir | is-empty) {
        $root | path join "artifacts" "generated" "T036"
    } else {
        $out_dir
    })
    let rows = (source-rows $tables_root)
    let checksum = (source-checksum $tables_root)
    mkdir $out_dir

    let bootstrap_nu = $"($out_dir)/bootstrap.nu"
    let bootstrap_sh = $"($out_dir)/bootstrap.sh"

    render-nu $rows $checksum $timestamp | save -f $bootstrap_nu
    render-sh $rows $checksum $timestamp | save -f $bootstrap_sh

    let manifest = [
        (manifest-row "bootstrap_nu" $bootstrap_nu "nushell" $checksum $timestamp)
        (manifest-row "bootstrap_sh" $bootstrap_sh "posix_shell" $checksum $timestamp)
    ]

    if ($manifest_out | is-not-empty) {
        $manifest | to csv | save --force $manifest_out
    }

    if $json {
        $manifest | to json
    } else {
        $manifest
    }
}
